import { ScreenConfig } from "./types";

const yn = ["", "Y", "N"];
const roleCodes = [
  "R01",
  "R02",
  "R03",
  "R04",
  "R05",
  "R06",
  "R07",
  "R08",
  "R09",
];
const permissionLevels = ["NONE", "READ", "WRITE"];
const scopes = ["SELF", "ORG", "ALL"];
const statuses = ["", "ACTIVE", "REVOKED", "EXPIRED"];
const assignmentTypes = ["POSITION", "MANUAL"];
const targetTypes = ["ROLE", "ORGANIZATION", "USER"];

export const screens: ScreenConfig[] = [
  {
    id: "SCR-USER-MGMT",
    title: "사용자 관리",
    route: "/system/users",
    menuPath: "시스템 관리 > 사용자·조직 관리 > 사용자 관리",
    goal: "교번·성명·소속·직급·재직상태·역할·사용여부로 검색하고 KORUS 원천필드가 아닌 시스템 사용여부와 업무 역할만 저장합니다.",
    archetype: "search-list-detail",
    endpoint: "/api/users",
    detailPath: (row) => (row.userId ? `/api/users/${row.userId}` : null),
    updatePath: (row) => (row.userId ? `/api/users/${row.userId}/usage` : null),
    extraAction: "userRoles",
    idKey: "userId",
    filters: [
      { key: "staffNo", label: "교번" },
      { key: "name", label: "성명" },
      { key: "orgCode", label: "소속" },
      { key: "rankName", label: "직급" },
      { key: "employmentStatus", label: "재직상태" },
      {
        key: "roleCode",
        label: "역할",
        type: "select",
        options: ["", ...roleCodes],
      },
      { key: "systemEnabled", label: "사용여부", type: "select", options: yn },
    ],
    columns: [
      { key: "staffNo", label: "교번" },
      { key: "displayName", label: "성명" },
      { key: "orgName", label: "소속" },
      { key: "rankName", label: "직급" },
      { key: "employmentStatus", label: "재직상태" },
      { key: "roleCodes", label: "역할" },
      { key: "systemEnabled", label: "사용여부" },
      { key: "positionName", label: "보직" },
      { key: "retirementDate", label: "퇴직일자" },
      { key: "lastSyncedAt", label: "최종 동기화" },
    ],
    fields: [
      { key: "staffNo", label: "교번", readonly: true },
      { key: "displayName", label: "성명", readonly: true },
      { key: "orgName", label: "소속", readonly: true },
      { key: "rankName", label: "직급", readonly: true },
      { key: "positionName", label: "보직", readonly: true },
      { key: "retirementDate", label: "퇴직일자", readonly: true },
      { key: "lastSyncedAt", label: "최종 동기화", readonly: true },
      {
        key: "systemEnabled",
        label: "시스템 사용여부",
        type: "select",
        options: ["Y", "N"],
      },
      {
        key: "roleCodes",
        label: "업무 역할",
        type: "roles",
        options: roleCodes,
      },
      {
        key: "reason",
        label: "변경 사유",
        type: "textarea",
        placeholder: "변경 이력에 남길 사유",
      },
    ],
  },
  {
    id: "SCR-ORG-MGMT",
    title: "조직 관리",
    route: "/system/organizations",
    menuPath: "시스템 관리 > 사용자·조직 관리 > 조직 관리",
    goal: "조직코드 기준 목록과 계층을 함께 보고 상위조직/적용기간 변경 이력을 저장합니다.",
    archetype: "tree-editor",
    endpoint: "/api/organizations",
    treeEndpoint: "/api/organizations/tree",
    updatePath: (row) =>
      row.orgCode ? `/api/organizations/${row.orgCode}/relationship` : null,
    idKey: "orgCode",
    filters: [
      { key: "orgCode", label: "조직코드" },
      { key: "orgName", label: "조직명" },
      {
        key: "orgType",
        label: "조직유형",
        type: "select",
        options: ["", "DEPARTMENT", "COLLEGE", "ADMIN"],
      },
    ],
    columns: [
      { key: "orgCode", label: "조직코드" },
      { key: "orgName", label: "조직명" },
      { key: "orgType", label: "조직유형" },
      { key: "parentOrgCode", label: "상위조직" },
      { key: "effectiveStartDate", label: "적용 시작" },
      { key: "effectiveEndDate", label: "적용 종료" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      { key: "orgCode", label: "조직코드", readonly: true },
      { key: "orgName", label: "조직명", readonly: true },
      { key: "parentOrgCode", label: "상위조직" },
      { key: "orgType", label: "조직유형", readonly: true },
      { key: "effectiveStartDate", label: "적용 시작일", type: "date" },
      { key: "effectiveEndDate", label: "적용 종료일", type: "date" },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
  },
  {
    id: "SCR-ROLE-MGMT",
    title: "역할 관리",
    route: "/system/roles",
    menuPath: "시스템 관리 > 역할·권한 관리 > 역할 관리",
    goal: "R01~R09 역할 목적을 조회하고 역할코드는 고정한 채 부여 기준과 데이터 범위 기본값을 관리합니다.",
    archetype: "effective-period",
    endpoint: "/api/roles",
    createPath: "/api/roles",
    updatePath: (row) => (row.roleCode ? `/api/roles/${row.roleCode}` : null),
    idKey: "roleCode",
    filters: [{ key: "filter", label: "역할코드·역할명" }],
    columns: [
      { key: "roleCode", label: "역할코드" },
      { key: "roleName", label: "역할명" },
      { key: "purpose", label: "목적" },
      { key: "grantCriteria", label: "부여 기준" },
      { key: "defaultDataScope", label: "데이터 범위" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      {
        key: "roleCode",
        label: "역할코드",
        type: "select",
        options: roleCodes,
        immutable: true,
      },
      { key: "roleName", label: "역할명" },
      { key: "purpose", label: "목적", type: "textarea" },
      { key: "grantCriteria", label: "부여 기준", type: "textarea" },
      {
        key: "defaultDataScope",
        label: "데이터 범위 기본값",
        type: "select",
        options: scopes,
      },
      {
        key: "isActive",
        label: "사용여부",
        type: "select",
        options: ["Y", "N"],
      },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
    newRecord: { roleCode: "R09", defaultDataScope: "ALL", isActive: "Y" },
  },
  {
    id: "SCR-USER-ROLE",
    title: "사용자 역할 관리",
    route: "/system/user-roles",
    menuPath: "시스템 관리 > 역할·권한 관리 > 사용자 역할 관리",
    goal: "사용자별 현재 역할과 유효기간을 조회하고 수동/보직 기반 역할 부여·변경·회수를 기록합니다.",
    archetype: "effective-period",
    endpoint: "/api/user-roles",
    createPath: "/api/user-roles",
    updatePath: (row) =>
      row.assignmentId ? `/api/user-roles/${row.assignmentId}` : null,
    extraAction: "revokeUserRole",
    idKey: "assignmentId",
    filters: [
      { key: "userId", label: "사용자 ID" },
      {
        key: "roleCode",
        label: "역할",
        type: "select",
        options: ["", ...roleCodes],
      },
      { key: "status", label: "상태", type: "select", options: statuses },
    ],
    columns: [
      { key: "displayName", label: "사용자" },
      { key: "roleCode", label: "역할코드" },
      { key: "roleName", label: "역할명" },
      { key: "assignmentType", label: "부여구분" },
      { key: "approvedByName", label: "승인자" },
      { key: "effectiveStartDate", label: "유효 시작" },
      { key: "effectiveEndDate", label: "유효 종료" },
      { key: "status", label: "상태" },
    ],
    fields: [
      { key: "userId", label: "사용자 ID" },
      { key: "roleCode", label: "역할", type: "select", options: roleCodes },
      {
        key: "assignmentType",
        label: "부여구분",
        type: "select",
        options: assignmentTypes,
      },
      { key: "approvedByUserId", label: "승인자 ID" },
      { key: "effectiveStartDate", label: "유효 시작일", type: "date" },
      { key: "effectiveEndDate", label: "유효 종료일", type: "date" },
      {
        key: "status",
        label: "상태",
        type: "select",
        options: statuses.slice(1),
      },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
    newRecord: { assignmentType: "MANUAL", status: "ACTIVE" },
  },
  {
    id: "SCR-MENU-PERMISSION",
    title: "메뉴 권한 관리",
    route: "/system/menu-permissions",
    menuPath: "시스템 관리 > 역할·권한 관리 > 메뉴 권한 관리",
    goal: "역할·조직·사용자 대상별 메뉴 접근 수준을 조회·저장하고 UI 메뉴와 서버 접근통제를 동일 데이터로 맞춥니다.",
    archetype: "permission-matrix",
    endpoint: "/api/menu-permissions",
    updatePath: () => "/api/menu-permissions",
    extraAction: "menuPermissions",
    idKey: "permissionId",
    filters: [
      {
        key: "targetType",
        label: "대상 유형",
        type: "select",
        options: ["", ...targetTypes],
      },
      { key: "targetId", label: "대상 ID" },
      { key: "menuId", label: "메뉴 ID" },
    ],
    columns: [
      { key: "targetType", label: "대상 유형" },
      { key: "targetId", label: "대상 ID" },
      { key: "menuName", label: "메뉴" },
      { key: "permissionLevel", label: "권한 수준" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      {
        key: "targetType",
        label: "대상 유형",
        type: "select",
        options: targetTypes,
      },
      { key: "targetId", label: "대상 ID" },
      { key: "menuId", label: "메뉴 ID", readonly: true },
      { key: "menuName", label: "메뉴", readonly: true },
      {
        key: "permissionLevel",
        label: "권한 수준",
        type: "select",
        options: permissionLevels,
      },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
  },
  {
    id: "SCR-MENU-STRUCTURE",
    title: "메뉴 구조 관리",
    route: "/system/menu-structure",
    menuPath: "시스템 관리 > 메뉴 관리 > 메뉴 구조 관리",
    goal: "대메뉴·중메뉴·소메뉴 계층을 보고 부모메뉴 변경과 동일 계층 표시순서 재정렬을 수행합니다.",
    archetype: "tree-editor",
    endpoint: "/api/menus",
    treeEndpoint: "/api/menus/tree",
    updatePath: (row) =>
      row.menuId ? `/api/menus/${row.menuId}/parent` : null,
    extraAction: "menuReorder",
    idKey: "menuId",
    filters: [
      { key: "menuName", label: "메뉴명" },
      { key: "isActive", label: "사용여부", type: "select", options: yn },
    ],
    columns: [
      { key: "menuId", label: "메뉴ID" },
      { key: "parentMenuId", label: "상위 메뉴" },
      { key: "menuName", label: "메뉴명" },
      { key: "routePath", label: "URL" },
      { key: "displayOrder", label: "표시순서" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      { key: "menuId", label: "선택 메뉴", readonly: true },
      { key: "menuName", label: "메뉴명", readonly: true },
      { key: "parentMenuId", label: "새 부모메뉴" },
      { key: "displayOrder", label: "동일 계층 표시순서", type: "number" },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
  },
  {
    id: "SCR-MENU-INFO",
    title: "메뉴 정보 관리",
    route: "/system/menu-info",
    menuPath: "시스템 관리 > 메뉴 관리 > 메뉴 정보 관리",
    goal: "메뉴명·화면ID·URL·아이콘·업무구분·설명을 조회·등록·수정하여 메뉴와 실행 화면을 연결합니다.",
    archetype: "content-editor",
    endpoint: "/api/menus",
    detailPath: (row) => (row.menuId ? `/api/menus/${row.menuId}` : null),
    createPath: "/api/menus",
    updatePath: (row) => (row.menuId ? `/api/menus/${row.menuId}` : null),
    idKey: "menuId",
    filters: [
      { key: "menuName", label: "메뉴명" },
      { key: "businessCategory", label: "업무구분" },
      { key: "isActive", label: "사용여부", type: "select", options: yn },
    ],
    columns: [
      { key: "menuName", label: "메뉴명" },
      { key: "screenId", label: "화면ID" },
      { key: "routePath", label: "URL" },
      { key: "iconName", label: "아이콘" },
      { key: "businessCategory", label: "업무구분" },
      { key: "description", label: "설명" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      { key: "menuId", label: "메뉴ID", readonly: true },
      { key: "menuName", label: "메뉴명" },
      { key: "screenId", label: "화면ID" },
      { key: "routePath", label: "URL/route" },
      { key: "iconName", label: "아이콘" },
      { key: "businessCategory", label: "업무구분" },
      { key: "description", label: "설명", type: "textarea" },
      { key: "displayOrder", label: "표시순서", type: "number" },
      {
        key: "isActive",
        label: "사용여부",
        type: "select",
        options: ["Y", "N"],
      },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
    newRecord: { isActive: "Y", displayOrder: 99 },
  },
  {
    id: "SCR-CODE-GROUP",
    title: "코드그룹 관리",
    route: "/system/code-groups",
    menuPath: "시스템 관리 > 공통코드 관리 > 코드그룹 관리",
    goal: "코드그룹을 조회하고 그룹ID·명칭·설명·관리부서를 등록·수정하며 선택 그룹의 상세코드 목록으로 이동합니다.",
    archetype: "search-list-detail",
    endpoint: "/api/code-groups",
    detailPath: (row) =>
      row.groupId ? `/api/code-groups/${row.groupId}` : null,
    createPath: "/api/code-groups",
    updatePath: (row) =>
      row.groupId ? `/api/code-groups/${row.groupId}` : null,
    extraAction: "codeGroupDetailLink",
    idKey: "groupId",
    filters: [
      { key: "groupId", label: "그룹ID" },
      { key: "groupName", label: "명칭" },
      { key: "managingDepartment", label: "관리부서" },
      { key: "isActive", label: "사용여부", type: "select", options: yn },
    ],
    columns: [
      { key: "groupId", label: "그룹ID" },
      { key: "groupName", label: "명칭" },
      { key: "description", label: "설명" },
      { key: "managingDepartment", label: "관리부서" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      { key: "groupId", label: "그룹ID" },
      { key: "groupName", label: "명칭" },
      { key: "managingDepartment", label: "관리부서" },
      {
        key: "isActive",
        label: "사용여부",
        type: "select",
        options: ["Y", "N"],
      },
      { key: "description", label: "설명", type: "textarea" },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
    newRecord: { isActive: "Y" },
  },
  {
    id: "SCR-CODE-DETAIL",
    title: "상세코드 관리",
    route: "/system/code-details",
    menuPath: "시스템 관리 > 공통코드 관리 > 상세코드 관리",
    goal: "코드그룹별 상세코드를 조회하고 코드값·코드명·상위코드·정렬순서·추가속성·유효기간을 관리합니다.",
    archetype: "tree-editor",
    endpoint: "/api/code-details",
    createPath: "/api/code-details",
    updatePath: (row) =>
      row.codeId ? `/api/code-details/${row.codeId}` : null,
    idKey: "codeId",
    filters: [
      { key: "groupId", label: "그룹ID" },
      { key: "codeValue", label: "코드값" },
      { key: "filter", label: "코드명" },
      { key: "isActive", label: "사용여부", type: "select", options: yn },
    ],
    columns: [
      { key: "groupId", label: "그룹ID" },
      { key: "codeValue", label: "코드값" },
      { key: "codeName", label: "코드명" },
      { key: "parentCodeId", label: "상위코드" },
      { key: "displayOrder", label: "정렬순서" },
      { key: "extraAttributes", label: "추가속성" },
      { key: "effectiveStartDate", label: "유효 시작" },
      { key: "effectiveEndDate", label: "유효 종료" },
      { key: "isActive", label: "사용" },
    ],
    fields: [
      { key: "groupId", label: "그룹ID" },
      { key: "codeValue", label: "코드값" },
      { key: "codeName", label: "코드명" },
      { key: "parentCodeId", label: "상위코드" },
      { key: "displayOrder", label: "정렬순서", type: "number" },
      { key: "extraAttributes", label: "추가속성(JSON object)", type: "json" },
      { key: "effectiveStartDate", label: "유효 시작일", type: "date" },
      { key: "effectiveEndDate", label: "유효 종료일", type: "date" },
      {
        key: "isActive",
        label: "사용여부",
        type: "select",
        options: ["Y", "N"],
      },
      { key: "reason", label: "변경 사유", type: "textarea" },
    ],
    newRecord: { displayOrder: 1, extraAttributes: "{}", isActive: "Y" },
  },
];

export const firstProtectedRoute = screens[0].route;
