package kr.ac.knue.fpe;

import org.apache.ibatis.jdbc.SQL;

import java.util.Map;

public class SqlProvider {
    public String users(Map<String,Object> p) {
        SQL sql = new SQL().SELECT("u.user_id as \"userId\", k.staff_no as \"staffNo\", k.staff_name as \"staffName\", k.organization_code as \"organizationCode\", o.organization_name as \"organizationName\", coalesce(oum.position_name,k.position_name) as \"positionName\", k.employment_status as \"employmentStatus\", k.retirement_date as \"retirementDate\", k.last_synced_at as \"lastSyncedAt\", u.system_enabled as \"systemEnabled\", coalesce(array_remove(array_agg(distinct ur.role_code), null), '{}') as \"roleCodes\"").FROM("user_accounts u").LEFT_OUTER_JOIN("korus_staff_snapshots k on k.staff_no=u.user_id").LEFT_OUTER_JOIN("organizations o on o.organization_code=k.organization_code").LEFT_OUTER_JOIN("organization_user_mappings oum on oum.user_id=u.user_id and oum.is_active=true").LEFT_OUTER_JOIN("user_roles ur on ur.user_id=u.user_id and ur.status='ACTIVE'").GROUP_BY("u.user_id,k.staff_no,k.staff_name,k.organization_code,o.organization_name,oum.position_name,k.position_name,k.employment_status,k.retirement_date,k.last_synced_at,u.system_enabled");
        like(sql,p,"staffNo","k.staff_no"); like(sql,p,"staffName","k.staff_name"); eq(sql,p,"organizationCode","k.organization_code"); like(sql,p,"positionName","coalesce(oum.position_name,k.position_name)"); eq(sql,p,"employmentStatus","k.employment_status"); eq(sql,p,"systemEnabled","u.system_enabled");
        if (has(p,"roleCode")) sql.HAVING("#{roleCode}=any(array_remove(array_agg(distinct ur.role_code), null))");
        return sql.toString()+" order by k.staff_no limit #{size} offset #{offset}";
    }
    public String organizations(Map<String,Object> p){ SQL sql=new SQL().SELECT("organization_code as \"organizationCode\", organization_name as \"organizationName\", organization_type as \"organizationType\", parent_organization_code as \"parentOrganizationCode\", effective_start_date as \"effectiveStartDate\", effective_end_date as \"effectiveEndDate\", is_active as \"active\"").FROM("organizations"); like(sql,p,"organizationCode","organization_code"); like(sql,p,"organizationName","organization_name"); eq(sql,p,"organizationType","organization_type"); eq(sql,p,"active","is_active"); return sql.toString()+" order by parent_organization_code nulls first, organization_code limit #{size} offset #{offset}"; }
    public String roles(Map<String,Object> p){ SQL sql=new SQL().SELECT("role_code as \"roleCode\", role_name as \"roleName\", purpose, grant_criteria as \"grantCriteria\", default_data_scope as \"defaultDataScope\", is_active as \"active\"").FROM("roles"); eq(sql,p,"roleCode","role_code"); like(sql,p,"roleName","role_name"); eq(sql,p,"active","is_active"); return sql.toString()+" order by role_code limit #{size} offset #{offset}"; }
    public String userRoles(Map<String,Object> p){ SQL sql=new SQL().SELECT("assignment_id as \"assignmentId\", user_id as \"userId\", role_code as \"roleCode\", assignment_source as \"assignmentSource\", effective_start_date as \"effectiveStartDate\", effective_end_date as \"effectiveEndDate\", approved_by as \"approvedBy\", status").FROM("user_roles"); eq(sql,p,"userId","user_id"); eq(sql,p,"roleCode","role_code"); eq(sql,p,"status","status"); return sql.toString()+" order by user_id, role_code limit #{size} offset #{offset}"; }
    public String menuPermissions(Map<String,Object> p){ SQL sql=new SQL().SELECT("permission_id as \"permissionId\", principal_type as \"principalType\", principal_id as \"principalId\", menu_id as \"menuId\", permission_effect as \"permissionEffect\", is_active as \"active\"").FROM("menu_permissions"); eq(sql,p,"principalType","principal_type"); eq(sql,p,"principalId","principal_id"); eq(sql,p,"menuId","menu_id"); return sql.toString()+" order by menu_id limit #{size} offset #{offset}"; }
    public String menus(Map<String,Object> p){ SQL sql=new SQL().SELECT("menu_id as \"menuId\", parent_menu_id as \"parentMenuId\", menu_level as \"menuLevel\", menu_name as \"menuName\", screen_id as \"screenId\", url, icon, business_category as \"businessCategory\", description, display_order as \"displayOrder\", is_active as \"active\"").FROM("menus"); like(sql,p,"menuName","menu_name"); like(sql,p,"screenId","screen_id"); like(sql,p,"url","url"); eq(sql,p,"active","is_active"); return sql.toString()+" order by parent_menu_id nulls first, display_order, menu_id limit #{size} offset #{offset}"; }
    public String codeGroups(Map<String,Object> p){ SQL sql=new SQL().SELECT("group_id as \"groupId\", group_name as \"groupName\", description, managing_department as \"managingDepartment\", is_active as \"active\"").FROM("code_groups"); like(sql,p,"groupId","group_id"); like(sql,p,"groupName","group_name"); like(sql,p,"managingDepartment","managing_department"); eq(sql,p,"active","is_active"); return sql.toString()+" order by group_id limit #{size} offset #{offset}"; }
    public String detailCodes(Map<String,Object> p){ SQL sql=new SQL().SELECT("group_id as \"groupId\", code_value as \"codeValue\", code_name as \"codeName\", parent_code_value as \"parentCodeValue\", sort_order as \"sortOrder\", additional_attributes as \"additionalAttributes\", valid_from as \"validFrom\", valid_to as \"validTo\", is_active as \"active\"").FROM("detail_codes").WHERE("group_id=#{groupId}"); like(sql,p,"codeValue","code_value"); like(sql,p,"codeName","code_name"); eq(sql,p,"active","is_active"); return sql.toString()+" order by sort_order, code_value"; }
    private boolean has(Map<String,Object> p,String k){ Object v=p.get(k); return v!=null && !(v instanceof String s && s.isBlank()); }
    private void eq(SQL sql,Map<String,Object> p,String k,String col){ if(has(p,k)) sql.WHERE(col+"=#{"+k+"}"); }
    private void like(SQL sql,Map<String,Object> p,String k,String col){ if(has(p,k)) sql.WHERE(col+" ilike concat('%',#{"+k+"},'%')"); }
}
