CREATE TABLE IF NOT EXISTS users (user_id varchar(64) PRIMARY KEY, login_id varchar(64) UNIQUE NOT NULL, password_hash varchar(255) NOT NULL, staff_no varchar(32) UNIQUE NOT NULL, display_name varchar(100) NOT NULL, system_use_yn char(1) NOT NULL CHECK (system_use_yn IN ('Y','N')), account_status varchar(20) NOT NULL CHECK (account_status IN ('ACTIVE','INACTIVE','LOCKED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE users IS '내부 로그인 계정과 시스템 사용여부를 관리하는 로컬 사용자 계정.';
COMMENT ON COLUMN users.system_use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN users.account_status IS 'ACTIVE:활성|INACTIVE:비활성|LOCKED:잠김';
CREATE TABLE IF NOT EXISTS korus_staff_snapshot (staff_no varchar(32) PRIMARY KEY, staff_name varchar(100) NOT NULL, organization_code varchar(32) NOT NULL, organization_name varchar(100) NOT NULL, rank_name varchar(50), employment_status varchar(20) NOT NULL CHECK (employment_status IN ('ACTIVE','LEAVE','RETIRED')), position_name varchar(100), retirement_date date, last_synced_at timestamptz NOT NULL);
COMMENT ON TABLE korus_staff_snapshot IS 'KORUS 원천 인사 정보를 로컬 조회 전용 Mock snapshot으로 제공한다.';
COMMENT ON COLUMN korus_staff_snapshot.employment_status IS 'ACTIVE:재직|LEAVE:휴직|RETIRED:퇴직';
CREATE TABLE IF NOT EXISTS organizations (organization_id varchar(64) PRIMARY KEY, organization_code varchar(32) UNIQUE NOT NULL, organization_name varchar(100) NOT NULL, organization_type varchar(30) NOT NULL CHECK (organization_type IN ('UNIVERSITY','GRADUATE_SCHOOL','COLLEGE','DEPARTMENT','OFFICE')), parent_organization_id varchar(64) REFERENCES organizations(organization_id), sort_order integer NOT NULL DEFAULT 1, effective_start_date date NOT NULL, effective_end_date date, status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED','PENDING')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE organizations IS '대학·대학원·단과대학·학과·부서의 기준일별 계층과 적용기간을 관리한다.';
COMMENT ON COLUMN organizations.status IS 'ACTIVE:활성|ENDED:종료|PENDING:준비중';
CREATE TABLE IF NOT EXISTS organization_user_assignments (assignment_id varchar(64) PRIMARY KEY, user_id varchar(64) REFERENCES users(user_id), organization_id varchar(64) REFERENCES organizations(organization_id), position_name varchar(100), valid_from date NOT NULL, valid_to date, status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE organization_user_assignments IS '사용자와 조직 또는 보직의 유효기간 관계를 보존한다.';
COMMENT ON COLUMN organization_user_assignments.status IS 'ACTIVE:활성|ENDED:종료';
CREATE TABLE IF NOT EXISTS roles (role_code varchar(3) PRIMARY KEY, role_name varchar(100) NOT NULL, purpose text, grant_criteria text, default_data_scope varchar(100), use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE roles IS 'R01~R09 업무 역할 기준정보와 데이터 범위 기본값을 관리한다.';
COMMENT ON COLUMN roles.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS user_roles (user_role_id varchar(64) PRIMARY KEY, user_id varchar(64) REFERENCES users(user_id), role_code varchar(3) REFERENCES roles(role_code), assignment_type varchar(30) NOT NULL CHECK (assignment_type IN ('POSITION_BASED','MANUAL')), valid_from date NOT NULL, valid_to date, approver_user_id varchar(64), status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE user_roles IS '사용자별 역할 부여·회수와 유효기간 및 승인자 기록을 저장한다.';
COMMENT ON COLUMN user_roles.approver_user_id IS 'users.user_id 참조 의도 (FK 미선언)';
COMMENT ON COLUMN user_roles.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:만료';
CREATE TABLE IF NOT EXISTS menus (menu_id varchar(64) PRIMARY KEY, parent_menu_id varchar(64) REFERENCES menus(menu_id), menu_name varchar(100) NOT NULL, level varchar(20) NOT NULL CHECK (level IN ('TOP','MIDDLE','SCREEN')), screen_id varchar(64), url varchar(200), icon varchar(80), business_category varchar(40), description text, sort_order integer NOT NULL DEFAULT 1, status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE','PENDING')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE menus IS '시스템 관리 메뉴 계층과 화면 실행정보를 관리한다.';
COMMENT ON COLUMN menus.status IS 'ACTIVE:활성|INACTIVE:비활성|PENDING:준비중';
CREATE TABLE IF NOT EXISTS menu_permissions (permission_id varchar(64) PRIMARY KEY, target_type varchar(20) NOT NULL CHECK (target_type IN ('ROLE','ORGANIZATION','USER')), target_id varchar(64) NOT NULL, menu_id varchar(64) REFERENCES menus(menu_id), access_decision varchar(10) NOT NULL CHECK (access_decision IN ('ALLOW','DENY','UNSET')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(target_type,target_id,menu_id));
COMMENT ON TABLE menu_permissions IS '역할·조직·사용자별 메뉴 접근 허용 여부를 저장한다.';
COMMENT ON COLUMN menu_permissions.target_id IS 'roles.role_code, organizations.organization_id, users.user_id 참조 의도 (다형 FK 미선언)';
COMMENT ON COLUMN menu_permissions.access_decision IS 'ALLOW:허용|DENY:차단|UNSET:미설정';
CREATE TABLE IF NOT EXISTS code_groups (group_id varchar(64) PRIMARY KEY, group_name varchar(100) NOT NULL, description text, managing_department varchar(100), use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE code_groups IS '공통 상세코드를 묶는 코드그룹 기준정보를 관리한다.';
COMMENT ON COLUMN code_groups.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS detail_codes (detail_code_id varchar(64) PRIMARY KEY, group_id varchar(64) REFERENCES code_groups(group_id), code_value varchar(64) NOT NULL, code_name varchar(100) NOT NULL, parent_detail_code_id varchar(64) REFERENCES detail_codes(detail_code_id), sort_order integer NOT NULL DEFAULT 1, additional_attributes jsonb NOT NULL DEFAULT '{}'::jsonb, valid_from date, valid_to date, use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(group_id, code_value));
COMMENT ON TABLE detail_codes IS '코드그룹별 상세코드와 계층, 정렬순서, 유효기간, 추가속성을 관리한다.';
COMMENT ON COLUMN detail_codes.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS sessions (session_id varchar(64) PRIMARY KEY, user_id varchar(64) REFERENCES users(user_id), status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON TABLE sessions IS '로그인 사용자 세션과 보호 API 인증 상태를 저장한다.';
COMMENT ON COLUMN sessions.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:만료';
CREATE TABLE IF NOT EXISTS change_history (history_id varchar(64) PRIMARY KEY, entity_name varchar(80) NOT NULL, entity_id varchar(64) NOT NULL, before_value jsonb NOT NULL, after_value jsonb NOT NULL, changed_by varchar(64), changed_at timestamptz NOT NULL DEFAULT now(), change_reason text);
COMMENT ON TABLE change_history IS '주요 관리 데이터의 변경 전후 값, 처리자, 처리일시, 사유 추적 구조이며 별도 감사로그 화면은 제공하지 않는다.';
COMMENT ON COLUMN change_history.changed_by IS 'users.user_id 참조 의도 (FK 미선언)';
CREATE INDEX IF NOT EXISTS idx_users_staff_no ON users(staff_no);
CREATE INDEX IF NOT EXISTS idx_korus_staff_org ON korus_staff_snapshot(organization_code);
CREATE INDEX IF NOT EXISTS idx_organizations_parent ON organizations(parent_organization_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_menus_parent ON menus(parent_menu_id);
CREATE INDEX IF NOT EXISTS idx_menu_permissions_target ON menu_permissions(target_type,target_id);
CREATE INDEX IF NOT EXISTS idx_detail_codes_group ON detail_codes(group_id);
