CREATE TABLE IF NOT EXISTS user_accounts (
  user_id varchar(64) PRIMARY KEY,
  username varchar(100) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  system_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE user_accounts IS '내부 로그인 계정과 시스템 사용여부의 로컬 mutable 기준.';
COMMENT ON COLUMN user_accounts.user_id IS 'korus_staff_snapshots.staff_no 참조 의도 (FK 미선언)';

CREATE TABLE IF NOT EXISTS organizations (
  organization_code varchar(64) PRIMARY KEY,
  organization_name varchar(200) NOT NULL,
  organization_type varchar(40) NOT NULL,
  parent_organization_code varchar(64) REFERENCES organizations(organization_code),
  effective_start_date date NOT NULL,
  effective_end_date date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE organizations IS '대학·대학원·단과대학·학과·부서의 조직 계층과 적용기간을 관리한다.';
COMMENT ON COLUMN organizations.organization_type IS 'UNIVERSITY:대학|GRADUATE_SCHOOL:대학원|COLLEGE:단과대학|DEPARTMENT:학과|OFFICE:부서';
COMMENT ON COLUMN organizations.parent_organization_code IS 'organizations.organization_code 참조 의도 (자기참조 FK 선언)';

CREATE TABLE IF NOT EXISTS korus_staff_snapshots (
  staff_no varchar(64) PRIMARY KEY,
  staff_name varchar(100) NOT NULL,
  organization_code varchar(64) NOT NULL REFERENCES organizations(organization_code),
  position_name varchar(100),
  employment_status varchar(40) NOT NULL,
  retirement_date date,
  last_synced_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE korus_staff_snapshots IS 'KORUS 원천 교직원 정보를 조회 전용 Mock snapshot으로 제공한다.';
COMMENT ON COLUMN korus_staff_snapshots.employment_status IS 'ACTIVE:재직|LEAVE:휴직|RETIRED:퇴직';

CREATE TABLE IF NOT EXISTS organization_user_mappings (
  mapping_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id varchar(64) NOT NULL REFERENCES user_accounts(user_id),
  organization_code varchar(64) NOT NULL REFERENCES organizations(organization_code),
  position_name varchar(100),
  effective_start_date date NOT NULL,
  effective_end_date date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE organization_user_mappings IS '사용자와 조직/보직 관계를 연결하여 목록 표시와 보직 기반 역할 구분에 활용한다.';

CREATE TABLE IF NOT EXISTS roles (
  role_code varchar(3) PRIMARY KEY,
  role_name varchar(100) NOT NULL,
  purpose text NOT NULL,
  grant_criteria text,
  default_data_scope text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT roles_role_code_check CHECK (role_code IN ('R01','R02','R03','R04','R05','R06','R07','R08','R09'))
);
COMMENT ON TABLE roles IS 'R01~R09 역할코드와 목적·부여기준·데이터 범위 기본값을 관리한다.';

CREATE TABLE IF NOT EXISTS user_roles (
  assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id varchar(64) NOT NULL REFERENCES user_accounts(user_id),
  role_code varchar(3) NOT NULL REFERENCES roles(role_code),
  assignment_source varchar(20) NOT NULL,
  effective_start_date date NOT NULL,
  effective_end_date date,
  approved_by varchar(64) NOT NULL REFERENCES user_accounts(user_id),
  status varchar(20) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_source_check CHECK (assignment_source IN ('POSITION_BASED','MANUAL')),
  CONSTRAINT user_roles_status_check CHECK (status IN ('ACTIVE','REVOKED','EXPIRED'))
);
COMMENT ON TABLE user_roles IS '사용자별 역할 부여·회수와 유효기간, 승인자, 보직/수동 구분을 저장한다.';
COMMENT ON COLUMN user_roles.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:기간만료';
COMMENT ON COLUMN user_roles.assignment_source IS 'POSITION_BASED:보직기반|MANUAL:수동';

CREATE TABLE IF NOT EXISTS menus (
  menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_menu_id bigint REFERENCES menus(menu_id),
  menu_level varchar(20) NOT NULL,
  menu_name varchar(200) NOT NULL,
  screen_id varchar(100),
  url varchar(300),
  icon varchar(100),
  business_category varchar(100),
  description text,
  display_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT menus_level_check CHECK (menu_level IN ('TOP','MIDDLE','SCREEN'))
);
COMMENT ON TABLE menus IS '대메뉴·중메뉴·소메뉴 계층, 표시순서, 화면 실행정보를 관리한다.';
COMMENT ON COLUMN menus.menu_level IS 'TOP:대메뉴|MIDDLE:중메뉴|SCREEN:화면';

CREATE TABLE IF NOT EXISTS menu_permissions (
  permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  principal_type varchar(20) NOT NULL,
  principal_id varchar(64) NOT NULL,
  menu_id bigint NOT NULL REFERENCES menus(menu_id),
  permission_effect varchar(10) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT menu_permissions_principal_check CHECK (principal_type IN ('ROLE','ORGANIZATION','USER')),
  CONSTRAINT menu_permissions_effect_check CHECK (permission_effect IN ('ALLOW','DENY'))
);
COMMENT ON TABLE menu_permissions IS '역할·조직·사용자 단위 메뉴 접근 허용/차단을 UI와 서버 접근통제에 동일 적용한다.';
COMMENT ON COLUMN menu_permissions.principal_type IS 'ROLE:역할|ORGANIZATION:조직|USER:사용자';
COMMENT ON COLUMN menu_permissions.permission_effect IS 'ALLOW:허용|DENY:차단';
COMMENT ON COLUMN menu_permissions.principal_id IS 'roles.role_code 또는 organizations.organization_code 또는 user_accounts.user_id 참조 의도 (principal_type별 FK 미선언)';

CREATE TABLE IF NOT EXISTS code_groups (
  group_id varchar(100) PRIMARY KEY,
  group_name varchar(200) NOT NULL,
  description text,
  managing_department varchar(200),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE code_groups IS '코드 묶음의 그룹ID, 명칭, 설명, 관리부서를 관리한다.';

CREATE TABLE IF NOT EXISTS detail_codes (
  group_id varchar(100) NOT NULL REFERENCES code_groups(group_id),
  code_value varchar(100) NOT NULL,
  code_name varchar(200) NOT NULL,
  parent_code_value varchar(100),
  sort_order integer NOT NULL,
  additional_attributes jsonb,
  valid_from date,
  valid_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, code_value)
);
COMMENT ON TABLE detail_codes IS '코드그룹별 코드값·코드명·상위코드·정렬순서·추가속성·유효기간을 관리한다.';
COMMENT ON COLUMN detail_codes.parent_code_value IS 'detail_codes.code_value 동일 group_id 내 참조 의도 (복합 FK 미선언)';
COMMENT ON COLUMN detail_codes.additional_attributes IS 'CommonCodeService.create/update 시 요청 JSON으로 갱신';

CREATE TABLE IF NOT EXISTS sessions (
  session_id varchar(128) PRIMARY KEY,
  user_id varchar(64) NOT NULL REFERENCES user_accounts(user_id),
  status varchar(20) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sessions_status_check CHECK (status IN ('ACTIVE','EXPIRED','REVOKED'))
);
COMMENT ON TABLE sessions IS 'HttpOnly SameSite=Lax session cookie 기반 인증 상태를 서버에서 저장한다.';
COMMENT ON COLUMN sessions.status IS 'ACTIVE:활성|EXPIRED:만료|REVOKED:회수';

CREATE TABLE IF NOT EXISTS change_histories (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_name varchar(100) NOT NULL,
  entity_key varchar(200) NOT NULL,
  change_type varchar(20) NOT NULL,
  before_value jsonb,
  after_value jsonb,
  changed_by varchar(64) NOT NULL REFERENCES user_accounts(user_id),
  changed_at timestamptz NOT NULL DEFAULT now(),
  reason text NOT NULL,
  CONSTRAINT change_histories_type_check CHECK (change_type IN ('CREATE','UPDATE','DISABLE','REVOKE'))
);
COMMENT ON TABLE change_histories IS '별도 감사로그 화면 없이 변경 전후 값, 처리자, 처리일시, 사유를 보존하는 내부 이력 구조.';
COMMENT ON COLUMN change_histories.change_type IS 'CREATE:등록|UPDATE:수정|DISABLE:비활성화|REVOKE:회수';

CREATE INDEX IF NOT EXISTS idx_korus_staff_org ON korus_staff_snapshots(organization_code);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_status ON user_roles(user_id, status);
CREATE INDEX IF NOT EXISTS idx_menus_parent_order ON menus(parent_menu_id, display_order);
CREATE INDEX IF NOT EXISTS idx_menu_permissions_principal ON menu_permissions(principal_type, principal_id);
CREATE INDEX IF NOT EXISTS idx_detail_codes_group_sort ON detail_codes(group_id, sort_order);
