INSERT INTO roles(role_code,role_name,purpose,grant_criteria,default_data_scope,use_yn) VALUES
('R01','교원','본인 관련 업무 수행','재직 교원','SELF','Y'),('R02','학과장','소속 학과 교원 확인','보직 기준','DEPARTMENT','Y'),('R03','단과대학(원) 행정실','단과대학 또는 대학원 행정 처리','부서 기준','COLLEGE','Y'),('R04','교수지원과','기준정보와 평가 행정 관리','부서 기준','ALL','Y'),('R05','산학협력단','연구비·지식재산 자료 관리','부서 기준','RESEARCH','Y'),('R06','입학인재관리과','입학·취업률 자료 관리','부서 기준','ADMISSION','Y'),('R07','실적부서','담당 실적 자료 관리','부서 기준','PERFORMANCE','Y'),('R08','점수산출 감사자','산출 과정과 근거 조회','감사 역할','AUDIT','Y'),('R09','시스템관리자','사용자·조직·메뉴·권한·코드 관리','시스템 관리자','ALL','Y') ON CONFLICT(role_code) DO NOTHING;
INSERT INTO korus_staff_snapshot(staff_no,staff_name,organization_code,organization_name,rank_name,employment_status,position_name,retirement_date,last_synced_at) VALUES ('KNUE-0001','관리자','ORG-EDU','교육학과','교수','ACTIVE','시스템관리자',NULL,now()),('KNUE-1001','홍길동','ORG-EDU','교육학과','부교수','ACTIVE','학과장',NULL,now()),('KNUE-2001','김교수','ORG-SCI','과학교육과','조교수','LEAVE','교원',NULL,now()) ON CONFLICT(staff_no) DO NOTHING;
INSERT INTO users(user_id,login_id,password_hash,staff_no,display_name,system_use_yn,account_status) VALUES ('admin-user','admin','admin','KNUE-0001','시스템 관리자','Y','ACTIVE'),('teacher-user','teacher','teacher','KNUE-1001','홍길동','Y','ACTIVE') ON CONFLICT(user_id) DO NOTHING;
INSERT INTO organizations(organization_id,organization_code,organization_name,organization_type,parent_organization_id,sort_order,effective_start_date,status) VALUES ('org-root','KNUE','한국교원대학교','UNIVERSITY',NULL,1,'2026-01-01','ACTIVE'),('org-college','COL-EDU','교육대학','COLLEGE','org-root',1,'2026-01-01','ACTIVE'),('org-edu','ORG-EDU','교육학과','DEPARTMENT','org-college',1,'2026-01-01','ACTIVE'),('org-sci','ORG-SCI','과학교육과','DEPARTMENT','org-college',2,'2026-01-01','ACTIVE'),('org-admin','ORG-ADMIN','교수지원과','OFFICE','org-root',3,'2026-01-01','ACTIVE') ON CONFLICT(organization_id) DO NOTHING;
INSERT INTO organization_user_assignments(assignment_id,user_id,organization_id,position_name,valid_from,status) VALUES ('assign-admin','admin-user','org-admin','시스템관리자','2026-01-01','ACTIVE'),('assign-teacher','teacher-user','org-edu','학과장','2026-01-01','ACTIVE') ON CONFLICT(assignment_id) DO NOTHING;
INSERT INTO user_roles(user_role_id,user_id,role_code,assignment_type,valid_from,status) VALUES ('ur-admin-r09','admin-user','R09','MANUAL','2026-01-01','ACTIVE'),('ur-teacher-r01','teacher-user','R01','POSITION_BASED','2026-01-01','ACTIVE') ON CONFLICT(user_role_id) DO NOTHING;
INSERT INTO menus(menu_id,parent_menu_id,menu_name,level,screen_id,url,icon,business_category,description,sort_order,status) VALUES
('menu-system',NULL,'시스템 관리','TOP','SYSTEM-SMOKE-DASHBOARD','/system','settings','CMN','시스템 관리 대시보드',1,'ACTIVE'),
('menu-user-org','menu-system','사용자·조직 관리','MIDDLE',NULL,NULL,'users','CMN','사용자와 조직 관리',10,'ACTIVE'),
('menu-users','menu-user-org','사용자 관리','SCREEN','CMN-USER-MGMT','/system/users','user','CMN','KORUS snapshot 기반 사용자 관리',11,'ACTIVE'),
('menu-orgs','menu-user-org','조직 관리','SCREEN','CMN-ORG-MGMT','/system/organizations','tree','CMN','조직 계층 관리',12,'ACTIVE'),
('menu-role-auth','menu-system','역할·권한 관리','MIDDLE',NULL,NULL,'shield','CMN','역할과 메뉴 권한 관리',20,'ACTIVE'),
('menu-roles','menu-role-auth','역할 관리','SCREEN','CMN-ROLE-MGMT','/system/roles','key','CMN','R01~R09 역할 관리',21,'ACTIVE'),
('menu-user-roles','menu-role-auth','사용자 역할 관리','SCREEN','CMN-USER-ROLE-MGMT','/system/user-roles','badge','CMN','사용자별 역할 부여 관리',22,'ACTIVE'),
('menu-perms','menu-role-auth','메뉴 권한 관리','SCREEN','CMN-MENU-AUTH-MGMT','/system/menu-permissions','lock','CMN','메뉴 접근권한 matrix',23,'ACTIVE'),
('menu-menu','menu-system','메뉴 관리','MIDDLE',NULL,NULL,'menu','CMN','메뉴 구조와 정보 관리',30,'ACTIVE'),
('menu-structure','menu-menu','메뉴 구조 관리','SCREEN','CMN-MENU-STRUCT-MGMT','/system/menu-structure','sitemap','CMN','메뉴 계층 관리',31,'ACTIVE'),
('menu-info','menu-menu','메뉴 정보 관리','SCREEN','CMN-MENU-INFO-MGMT','/system/menu-info','edit','CMN','메뉴 실행정보 관리',32,'ACTIVE'),
('menu-code','menu-system','공통코드 관리','MIDDLE',NULL,NULL,'code','CMN','공통코드 기준정보',40,'ACTIVE'),
('menu-code-groups','menu-code','코드그룹 관리','SCREEN','CMN-CODE-GROUP-MGMT','/system/code-groups','folder','CMN','코드그룹 관리',41,'ACTIVE'),
('menu-detail-codes','menu-code','상세코드 관리','SCREEN','CMN-DETAIL-CODE-MGMT','/system/code-groups/USER_STATUS/detail-codes','list','CMN','상세코드 관리',42,'ACTIVE') ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO menu_permissions(permission_id,target_type,target_id,menu_id,access_decision) SELECT 'perm-r09-'||menu_id,'ROLE','R09',menu_id,'ALLOW' FROM menus ON CONFLICT(target_type,target_id,menu_id) DO NOTHING;
INSERT INTO menu_permissions(permission_id,target_type,target_id,menu_id,access_decision) VALUES ('perm-r01-deny-users','ROLE','R01','menu-users','DENY') ON CONFLICT(target_type,target_id,menu_id) DO NOTHING;
INSERT INTO code_groups(group_id,group_name,description,managing_department,use_yn) VALUES ('USER_STATUS','사용자 상태','사용자 계정과 재직 상태 선택값','교수지원과','Y'),('ORG_TYPE','조직 유형','조직 유형 선택값','교수지원과','Y') ON CONFLICT(group_id) DO NOTHING;
INSERT INTO detail_codes(detail_code_id,group_id,code_value,code_name,parent_detail_code_id,sort_order,additional_attributes,valid_from,use_yn) VALUES ('dc-user-active','USER_STATUS','ACTIVE','활성',NULL,1,'{}','2026-01-01','Y'),('dc-user-inactive','USER_STATUS','INACTIVE','비활성',NULL,2,'{}','2026-01-01','Y'),('dc-org-dept','ORG_TYPE','DEPARTMENT','학과',NULL,1,'{}','2026-01-01','Y') ON CONFLICT(group_id,code_value) DO NOTHING;
