CREATE TABLE IF NOT EXISTS entity_table_contract (
  entity_name varchar(100) PRIMARY KEY,
  label varchar(200) NOT NULL,
  purpose text NOT NULL,
  source_of_truth varchar(100) NOT NULL,
  lifecycle_status_owner varchar(100) NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE entity_table_contract IS 'data-model.md Entity/Table Contract section을 DB 검증 가능한 계약 원장으로 보존한다.';
COMMENT ON COLUMN entity_table_contract.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS canonical_field_ledger (
  entity_name varchar(100) NOT NULL,
  field_name varchar(100) NOT NULL,
  data_type varchar(100) NOT NULL,
  constraint_summary text NOT NULL,
  enum_values text[],
  relationship_summary text,
  audit_delete_policy text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (entity_name, field_name)
);
COMMENT ON TABLE canonical_field_ledger IS 'data-model.md Canonical Field Ledger의 엔티티별 필드·제약·관계·감사 정책을 저장한다.';
COMMENT ON COLUMN canonical_field_ledger.enum_values IS 'Spec Agent data-model.md 생성 시 허용 enum 값 배열로 갱신';
COMMENT ON COLUMN canonical_field_ledger.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS field_mutability_matrix (
  matrix_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_name varchar(100) NOT NULL,
  field_name varchar(100) NOT NULL,
  source_of_truth varchar(100) NOT NULL,
  mutable_states text NOT NULL,
  editable_screen_id varchar(100),
  operation_id varchar(100),
  api_path varchar(300),
  validation_summary text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE field_mutability_matrix IS '필드별 readonly/mutable 상태, 편집 화면, OpenAPI operation 연결과 서버 검증 계약을 저장한다.';
COMMENT ON COLUMN field_mutability_matrix.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS relationship_contract (
  relationship_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_table varchar(100) NOT NULL,
  from_field varchar(100) NOT NULL,
  to_table varchar(100) NOT NULL,
  to_field varchar(100) NOT NULL,
  cardinality varchar(20) NOT NULL,
  policy text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE relationship_contract IS 'data-model.md Relationship Contract의 FK 의도, cardinality, 삭제·이력 정책을 DB 계약으로 저장한다.';
COMMENT ON COLUMN relationship_contract.cardinality IS 'N:1:N대1|1:N:1대N|1:1:1대1|N:M:N대M';
COMMENT ON COLUMN relationship_contract.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS validation_rule_matrix (
  rule_key varchar(100) PRIMARY KEY,
  field_scope text NOT NULL,
  operation_id varchar(100) NOT NULL,
  expected_error_behavior text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE validation_rule_matrix IS 'data-model.md Validation Rule Matrix의 입력 필드, operationId, 오류 응답 계약을 저장한다.';
COMMENT ON COLUMN validation_rule_matrix.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS seed_data_contract (
  seed_id varchar(100) PRIMARY KEY,
  entity_table varchar(100) NOT NULL,
  minimal_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  purpose_test_acceptance text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE seed_data_contract IS '로컬 smoke와 acceptance test에 필요한 안전한 synthetic seed fixture 계약을 저장한다.';
COMMENT ON COLUMN seed_data_contract.minimal_fields IS 'Spec Agent data-model.md 생성 시 seed 최소 필드 JSON으로 갱신';
COMMENT ON COLUMN seed_data_contract.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS screen_a_p_i_reference (
  screen_id varchar(100) PRIMARY KEY,
  route varchar(300) NOT NULL,
  primary_entities text[] NOT NULL DEFAULT '{}',
  operation_ids text[] NOT NULL DEFAULT '{}',
  api_paths text[] NOT NULL DEFAULT '{}',
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE screen_a_p_i_reference IS '화면ID, route, primary entity, OpenAPI operationId/path 연결 계약을 저장한다.';
COMMENT ON COLUMN screen_a_p_i_reference.primary_entities IS 'Spec Agent data-model.md 생성 시 화면이 사용하는 primary entity 배열로 갱신';
COMMENT ON COLUMN screen_a_p_i_reference.operation_ids IS 'Spec Agent data-model.md 생성 시 OpenAPI operationId 배열로 갱신';
COMMENT ON COLUMN screen_a_p_i_reference.api_paths IS 'Spec Agent data-model.md 생성 시 API path 배열로 갱신';
COMMENT ON COLUMN screen_a_p_i_reference.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS state_transition_audit_retention_security (
  policy_key varchar(100) PRIMARY KEY,
  entity_table varchar(100) NOT NULL,
  field_name varchar(100),
  transition_or_policy text NOT NULL,
  security_classification varchar(100) NOT NULL,
  retention_policy text NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE state_transition_audit_retention_security IS '상태 전이, 변경 이력, 보존, 보안 분류 정책을 data-model.md와 DB 사이의 계약으로 저장한다.';
COMMENT ON COLUMN state_transition_audit_retention_security.security_classification IS 'PUBLIC:공개|INTERNAL:내부|SECRET_EQUIVALENT:secret동등';
COMMENT ON COLUMN state_transition_audit_retention_security.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE TABLE IF NOT EXISTS persistence_assumptions (
  assumption_key varchar(100) PRIMARY KEY,
  assumption_text text NOT NULL,
  technology_scope varchar(100) NOT NULL,
  canonical_ids text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE persistence_assumptions IS 'MyBatis/PostgreSQL/Flyway 등 영속성 구현 전제와 transaction 정책을 저장한다.';
COMMENT ON COLUMN persistence_assumptions.technology_scope IS 'BACKEND:백엔드|DATABASE:데이터베이스|INTEGRATION:통합';
COMMENT ON COLUMN persistence_assumptions.canonical_ids IS 'Spec Agent data-model.md 생성 시 canonical_id 배열로 갱신';

CREATE INDEX IF NOT EXISTS idx_canonical_field_ledger_entity ON canonical_field_ledger(entity_name);
CREATE INDEX IF NOT EXISTS idx_field_mutability_operation ON field_mutability_matrix(operation_id);
CREATE INDEX IF NOT EXISTS idx_relationship_contract_from ON relationship_contract(from_table, from_field);
CREATE INDEX IF NOT EXISTS idx_relationship_contract_to ON relationship_contract(to_table, to_field);
CREATE INDEX IF NOT EXISTS idx_validation_rule_operation ON validation_rule_matrix(operation_id);
CREATE INDEX IF NOT EXISTS idx_seed_data_contract_entity ON seed_data_contract(entity_table);
CREATE INDEX IF NOT EXISTS idx_screen_api_reference_route ON screen_a_p_i_reference(route);
CREATE INDEX IF NOT EXISTS idx_state_policy_entity ON state_transition_audit_retention_security(entity_table);

INSERT INTO entity_table_contract(entity_name, label, purpose, source_of_truth, lifecycle_status_owner, canonical_ids) VALUES
('user_accounts','사용자 계정','내부 로그인 계정과 시스템 사용여부의 로컬 mutable 기준','local DB','local DB mutable',ARRAY['REQ-004','REQ-028','REQ-047','REQ-048','REQ-089','REQ-090','REQ-102']),
('korus_staff_snapshots','KORUS 교직원 Mock snapshot','KORUS 원천 교원·조직·보직 정보의 조회 전용 Mock snapshot','KORUS Mock snapshot','readonly',ARRAY['REQ-003','REQ-019','REQ-044','REQ-049']),
('organizations','조직','조직 계층과 적용기간 변경 이력의 로컬 관리 기준','local DB','local DB mutable',ARRAY['REQ-029','REQ-050','REQ-101']),
('organization_user_mappings','보직/조직 사용자 매핑','사용자와 조직/보직 관계를 연결한다','local DB','local DB mutable',ARRAY['REQ-028','REQ-031','REQ-051']),
('roles','역할','R01~R09 역할코드와 역할명, 목적, 부여 기준을 관리한다','local DB','local DB mutable',ARRAY['REQ-008','REQ-009','REQ-010','REQ-011','REQ-012','REQ-013','REQ-014','REQ-015','REQ-016','REQ-030','REQ-052','REQ-093']),
('user_roles','사용자 역할','사용자별 역할, 유효기간, 승인자, 부여 구분을 기록한다','local DB','local DB mutable',ARRAY['REQ-031','REQ-053','REQ-091']),
('menus','메뉴','대·중·소 메뉴 계층, 실행 화면, 표시순서를 관리한다','local DB','local DB mutable',ARRAY['REQ-033','REQ-034','REQ-054','REQ-094','REQ-095','REQ-096','REQ-097','REQ-098','REQ-099']),
('menu_permissions','메뉴 권한','역할·조직·사용자 단위 메뉴 접근 허용/차단을 저장한다','local DB','local DB mutable',ARRAY['REQ-017','REQ-018','REQ-032','REQ-055','REQ-100']),
('code_groups','코드그룹','코드 묶음의 그룹ID, 명칭, 설명, 관리부서를 관리한다','local DB','local DB mutable',ARRAY['REQ-035','REQ-056']),
('detail_codes','상세코드','코드그룹별 코드값·코드명·상위코드·정렬순서·추가속성을 관리한다','local DB','local DB mutable',ARRAY['REQ-022','REQ-036','REQ-057']),
('sessions','세션','HttpOnly SameSite=Lax session cookie 기반 인증 상태를 저장한다','server-side session store','server controlled',ARRAY['REQ-047','REQ-058','REQ-061','REQ-070']),
('change_histories','변경 이력','등록·수정·삭제성 처리의 변경 전후 값, 처리자, 사유를 저장한다','local DB','append-only history',ARRAY['REQ-021'])
ON CONFLICT (entity_name) DO UPDATE SET
  label = EXCLUDED.label,
  purpose = EXCLUDED.purpose,
  source_of_truth = EXCLUDED.source_of_truth,
  lifecycle_status_owner = EXCLUDED.lifecycle_status_owner,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO canonical_field_ledger(entity_name, field_name, data_type, constraint_summary, enum_values, relationship_summary, audit_delete_policy, canonical_ids) VALUES
('user_accounts','user_id','varchar(64)','PK, 내부 사용자 식별자',NULL,'korus_staff_snapshots.staff_no 참조 의도','비활성화 우선, 변경 이력 보존',ARRAY['REQ-028','REQ-048']),
('user_accounts','password_hash','varchar(255)','not null, plaintext 금지',NULL,NULL,'secret-equivalent 로그/응답 노출 금지',ARRAY['REQ-047','REQ-089','REQ-090']),
('roles','role_code','varchar(3)','PK, immutable',ARRAY['R01','R02','R03','R04','R05','R06','R07','R08','R09'],NULL,'역할명 변경 후에도 role_code 유지',ARRAY['REQ-008','REQ-009','REQ-010','REQ-011','REQ-012','REQ-013','REQ-014','REQ-015','REQ-016','REQ-030']),
('user_roles','status','varchar(20)','not null',ARRAY['ACTIVE','REVOKED','EXPIRED'],NULL,'회수 시 물리삭제보다 REVOKED 상태 보존',ARRAY['REQ-031','REQ-053','REQ-060']),
('menus','menu_level','varchar(20)','not null',ARRAY['TOP','MIDDLE','SCREEN'],'menus.parent_menu_id 자기참조','사용 중 메뉴는 비활성화 우선',ARRAY['REQ-033','REQ-099']),
('menu_permissions','permission_effect','varchar(10)','not null',ARRAY['ALLOW','DENY'],'menus.menu_id 참조','권한 저장값은 UI와 서버 접근통제에 동일 적용',ARRAY['REQ-017','REQ-018','REQ-032']),
('detail_codes','additional_attributes','jsonb','nullable',NULL,'code_groups.group_id 참조','CommonCodeService.create/update 시 요청 JSON으로 갱신',ARRAY['REQ-036','REQ-057'])
ON CONFLICT (entity_name, field_name) DO UPDATE SET
  data_type = EXCLUDED.data_type,
  constraint_summary = EXCLUDED.constraint_summary,
  enum_values = EXCLUDED.enum_values,
  relationship_summary = EXCLUDED.relationship_summary,
  audit_delete_policy = EXCLUDED.audit_delete_policy,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO field_mutability_matrix(entity_name, field_name, source_of_truth, mutable_states, editable_screen_id, operation_id, api_path, validation_summary, canonical_ids) VALUES
('korus_staff_snapshots','*','KORUS Mock snapshot readonly','항상 readonly','USER_MANAGEMENT','listUsers','GET /api/admin/users','수정 요청 DTO에 포함하지 않는다',ARRAY['REQ-003','REQ-019','REQ-028','REQ-044']),
('user_accounts','system_enabled','local DB mutable','R09가 변경 가능','USER_MANAGEMENT','updateUserUsage','PATCH /api/admin/users/{userId}/usage','boolean required, reason required',ARRAY['REQ-004','REQ-020','REQ-028','REQ-062']),
('user_roles','role_code/effective_*','local DB mutable','R09가 부여·변경·회수','USER_MANAGEMENT','replaceUserRoles','PUT /api/admin/users/{userId}/roles','R01~R09 role_code, 기간 역전 금지',ARRAY['REQ-030','REQ-031','REQ-053','REQ-062']),
('organizations','parent_organization_code/effective_*','local DB mutable','R09가 변경 가능','ORGANIZATION_MANAGEMENT','updateOrganizationRelationships','PUT /api/admin/organizations/{organizationCode}/relationships','자기 parent 금지, 기간 역전 금지',ARRAY['REQ-029','REQ-063'])
ON CONFLICT DO NOTHING;

INSERT INTO relationship_contract(from_table, from_field, to_table, to_field, cardinality, policy, canonical_ids) VALUES
('organizations','parent_organization_code','organizations','organization_code','N:1','부모-자식 조직 관계는 적용기간과 함께 관리하고 변경 이력을 보존한다',ARRAY['REQ-029','REQ-050']),
('organization_user_mappings','user_id','user_accounts','user_id','N:1','사용자 소속/보직 연결은 목록 표시와 역할 구분에 사용한다',ARRAY['REQ-028','REQ-031','REQ-051']),
('user_roles','role_code','roles','role_code','N:1','부여 가능한 역할은 R01~R09 역할 seed 또는 관리 역할이다',ARRAY['REQ-030','REQ-031','REQ-052','REQ-053','REQ-093']),
('menu_permissions','menu_id','menus','menu_id','N:1','메뉴 권한 저장값은 UI 메뉴 노출과 서버 access control에 동일 적용한다',ARRAY['REQ-017','REQ-018','REQ-032','REQ-055']),
('detail_codes','group_id','code_groups','group_id','N:1','상세코드는 코드그룹별로 조회·등록·수정된다',ARRAY['REQ-035','REQ-036','REQ-056','REQ-057'])
ON CONFLICT DO NOTHING;

INSERT INTO validation_rule_matrix(rule_key, field_scope, operation_id, expected_error_behavior, canonical_ids) VALUES
('AUTH_CREDENTIAL','username,password','login','credential 오류는 4xx ApiError envelope를 반환하고 sessions row를 만들지 않는다',ARRAY['REQ-047','REQ-061','REQ-089','REQ-090']),
('USER_USAGE_REASON','userId,systemEnabled,reason','updateUserUsage','reason 누락은 field error를 반환한다',ARRAY['REQ-021','REQ-025','REQ-028']),
('ROLE_DATE_ORDER','role_code,effective dates,approved_by,reason','replaceUserRoles','R01~R09 외 role_code와 종료일<시작일은 field error',ARRAY['REQ-025','REQ-028','REQ-031']),
('ORG_RELATIONSHIP','organizationCode,parent,effective dates,reason','updateOrganizationRelationships','자기 parent 또는 종료일<시작일은 field error',ARRAY['REQ-021','REQ-025','REQ-029']),
('DETAIL_CODE_PERIOD','code_value,code_name,sort_order,valid_from,valid_to','updateDetailCode','valid_to가 valid_from보다 이전이면 field error',ARRAY['REQ-022','REQ-025','REQ-036'])
ON CONFLICT (rule_key) DO UPDATE SET
  field_scope = EXCLUDED.field_scope,
  operation_id = EXCLUDED.operation_id,
  expected_error_behavior = EXCLUDED.expected_error_behavior,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO seed_data_contract(seed_id, entity_table, minimal_fields, purpose_test_acceptance, canonical_ids) VALUES
('SEED-ADMIN','user_accounts','{"username":"admin","passwordStoredAs":"hash","systemEnabled":true}'::jsonb,'Docker Compose 직후 로그인 가능',ARRAY['REQ-089','REQ-090','REQ-092']),
('SEED-ADMIN-R09','user_roles','{"userId":"admin","roleCode":"R09","assignmentSource":"MANUAL","status":"ACTIVE"}'::jsonb,'시드 관리자가 시스템관리자 권한을 가짐',ARRAY['REQ-091','REQ-100']),
('SEED-ROLES','roles','{"roleCodes":["R01","R02","R03","R04","R05","R06","R07","R08","R09"]}'::jsonb,'역할 목록 조회와 권한 seed 기준',ARRAY['REQ-008','REQ-009','REQ-010','REQ-011','REQ-012','REQ-013','REQ-014','REQ-015','REQ-016','REQ-093']),
('SEED-R09-PERMISSIONS','menu_permissions','{"principalType":"ROLE","principalId":"R09","permissionEffect":"ALLOW"}'::jsonb,'R09가 9개 화면 조회 가능',ARRAY['REQ-027','REQ-100'])
ON CONFLICT (seed_id) DO UPDATE SET
  entity_table = EXCLUDED.entity_table,
  minimal_fields = EXCLUDED.minimal_fields,
  purpose_test_acceptance = EXCLUDED.purpose_test_acceptance,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO screen_a_p_i_reference(screen_id, route, primary_entities, operation_ids, api_paths, canonical_ids) VALUES
('LOGIN','/login',ARRAY['sessions','user_accounts'],ARRAY['login','logout','getCurrentUser'],ARRAY['POST /api/auth/login','POST /api/auth/logout','GET /api/auth/me'],ARRAY['REQ-061','REQ-070','REQ-072','REQ-089','REQ-090']),
('USER_MANAGEMENT','/system/users',ARRAY['user_accounts','korus_staff_snapshots','user_roles'],ARRAY['listUsers','updateUserUsage','replaceUserRoles'],ARRAY['GET /api/admin/users','PATCH /api/admin/users/{userId}/usage','PUT /api/admin/users/{userId}/roles'],ARRAY['REQ-028','REQ-062','REQ-073']),
('ORGANIZATION_MANAGEMENT','/system/organizations',ARRAY['organizations','organization_user_mappings'],ARRAY['listOrganizations','updateOrganizationRelationships'],ARRAY['GET /api/admin/organizations','PUT /api/admin/organizations/{organizationCode}/relationships'],ARRAY['REQ-029','REQ-063','REQ-074']),
('ROLE_MANAGEMENT','/system/roles',ARRAY['roles'],ARRAY['listRoles','createRole','updateRole'],ARRAY['GET /api/admin/roles','POST /api/admin/roles','PUT /api/admin/roles/{roleCode}'],ARRAY['REQ-030','REQ-064','REQ-075']),
('USER_ROLE_MANAGEMENT','/system/user-roles',ARRAY['user_roles'],ARRAY['listUserRoleAssignments','grantUserRole','revokeUserRole'],ARRAY['GET /api/admin/user-roles','POST /api/admin/user-roles','DELETE /api/admin/user-roles/{assignmentId}'],ARRAY['REQ-031','REQ-065','REQ-076']),
('MENU_PERMISSION_MANAGEMENT','/system/menu-permissions',ARRAY['menu_permissions','menus'],ARRAY['listMenuPermissions','saveMenuPermissions'],ARRAY['GET /api/admin/menu-permissions','PUT /api/admin/menu-permissions'],ARRAY['REQ-032','REQ-067','REQ-077']),
('MENU_STRUCTURE_MANAGEMENT','/system/menu-structure',ARRAY['menus'],ARRAY['getMenuTree','updateMenuStructure'],ARRAY['GET /api/admin/menus/tree','PUT /api/admin/menus/{menuId}/structure'],ARRAY['REQ-033','REQ-078']),
('MENU_INFO_MANAGEMENT','/system/menu-info',ARRAY['menus'],ARRAY['listMenus','createMenu','updateMenu'],ARRAY['GET /api/admin/menus','POST /api/admin/menus','PUT /api/admin/menus/{menuId}'],ARRAY['REQ-034','REQ-066','REQ-079']),
('CODE_GROUP_MANAGEMENT','/system/code-groups',ARRAY['code_groups'],ARRAY['listCodeGroups','createCodeGroup','updateCodeGroup'],ARRAY['GET /api/admin/code-groups','POST /api/admin/code-groups','PUT /api/admin/code-groups/{groupId}'],ARRAY['REQ-035','REQ-068','REQ-080']),
('DETAIL_CODE_MANAGEMENT','/system/code-groups/{groupId}/codes',ARRAY['detail_codes','code_groups'],ARRAY['listDetailCodes','createDetailCode','updateDetailCode'],ARRAY['GET /api/admin/code-groups/{groupId}/codes','POST /api/admin/code-groups/{groupId}/codes','PUT /api/admin/code-groups/{groupId}/codes/{codeValue}'],ARRAY['REQ-036','REQ-069','REQ-081'])
ON CONFLICT (screen_id) DO UPDATE SET
  route = EXCLUDED.route,
  primary_entities = EXCLUDED.primary_entities,
  operation_ids = EXCLUDED.operation_ids,
  api_paths = EXCLUDED.api_paths,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO state_transition_audit_retention_security(policy_key, entity_table, field_name, transition_or_policy, security_classification, retention_policy, canonical_ids) VALUES
('USER_ACCOUNT_DISABLE','user_accounts','system_enabled','true -> false이면 로그인과 보호 API 사용을 차단하고 change_histories에 기록한다','INTERNAL','비활성화 우선, 변경 이력 보존',ARRAY['REQ-021','REQ-028','REQ-070']),
('USER_ROLE_REVOKE','user_roles','status','ACTIVE -> REVOKED 또는 EXPIRED로 상태 전이한다','INTERNAL','물리삭제보다 상태 보존',ARRAY['REQ-031','REQ-060']),
('SESSION_STATUS','sessions','status','login ACTIVE, logout REVOKED, 만료 EXPIRED','SECRET_EQUIVALENT','session_id는 로그/응답 노출 금지',ARRAY['REQ-047','REQ-061']),
('PASSWORD_HASH','user_accounts','password_hash','plaintext 저장 금지','SECRET_EQUIVALENT','hash만 저장하고 원문 비밀번호 보존 금지',ARRAY['REQ-047','REQ-089','REQ-090'])
ON CONFLICT (policy_key) DO UPDATE SET
  entity_table = EXCLUDED.entity_table,
  field_name = EXCLUDED.field_name,
  transition_or_policy = EXCLUDED.transition_or_policy,
  security_classification = EXCLUDED.security_classification,
  retention_policy = EXCLUDED.retention_policy,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();

INSERT INTO persistence_assumptions(assumption_key, assumption_text, technology_scope, canonical_ids) VALUES
('PERSISTENCE_STACK','backend는 imperative + blocking MyBatis + PostgreSQL 16으로 구현한다','DATABASE',ARRAY['REQ-037','REQ-039','REQ-105','REQ-111']),
('MUTATION_HISTORY_TRANSACTION','모든 mutating operation은 service transaction 안에서 대상 table 변경과 change_histories 저장을 함께 처리한다','BACKEND',ARRAY['REQ-021','REQ-025']),
('KORUS_READONLY_PORT','KORUS Mock snapshot은 PersonnelInformationPort 뒤의 readonly adapter가 읽으며 실제 KORUS 접속은 하지 않는다','INTEGRATION',ARRAY['REQ-003','REQ-019','REQ-044'])
ON CONFLICT (assumption_key) DO UPDATE SET
  assumption_text = EXCLUDED.assumption_text,
  technology_scope = EXCLUDED.technology_scope,
  canonical_ids = EXCLUDED.canonical_ids,
  updated_at = now();
