package kr.ac.knue.facultyeval.system;

import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class AdminSqlProvider {
  public String listUsers(Map<String, Object> p) {
    SQL sql = new SQL().SELECT("u.user_id as \"userId\", u.login_id as \"loginId\", u.staff_no as \"staffNo\", u.display_name as \"displayName\", u.org_code as \"orgCode\", o.org_name as \"orgName\", u.position_name as \"positionName\", u.employment_status as \"employmentStatus\", u.system_enabled as \"systemEnabled\", s.rank_name as \"rankName\", s.retirement_date as \"retirementDate\", s.last_synced_at as \"lastSyncedAt\"")
      .FROM("app_user u left join organization o on o.org_code=u.org_code left join korus_staff_snapshot s on s.staff_no=u.staff_no");
    addLike(sql, p, "staffNo", "u.staff_no"); addLike(sql, p, "name", "u.display_name"); addEq(sql, p, "orgCode", "u.org_code"); addLike(sql, p, "rankName", "s.rank_name"); addEq(sql, p, "employmentStatus", "u.employment_status"); addEq(sql, p, "systemEnabled", "u.system_enabled");
    if (present(p, "roleCode")) { sql.WHERE("exists (select 1 from user_role_assignment ura where ura.user_id=u.user_id and ura.role_code=#{roleCode} and ura.status='ACTIVE')"); }
    sql.ORDER_BY("u.display_name"); return sql.toString();
  }
  public String listOrganizations(Map<String, Object> p) { SQL sql = base("organization", "org_code as \"orgCode\", org_name as \"orgName\", parent_org_code as \"parentOrgCode\", org_type as \"orgType\", effective_start_date as \"effectiveStartDate\", effective_end_date as \"effectiveEndDate\", is_active as \"isActive\""); addLike(sql,p,"orgCode","org_code"); addLike(sql,p,"orgName","org_name"); addEq(sql,p,"orgType","org_type"); sql.ORDER_BY("org_code"); return sql.toString(); }
  public String listRoles(Map<String, Object> p) { SQL sql = base("role", "role_code as \"roleCode\", role_name as \"roleName\", purpose, grant_criteria as \"grantCriteria\", default_data_scope as \"defaultDataScope\", is_active as \"isActive\""); addGenericFilter(sql,p,"role_code", "role_name", "purpose"); sql.ORDER_BY("role_code"); return sql.toString(); }
  public String listUserRoles(Map<String, Object> p) { SQL sql = new SQL().SELECT("a.assignment_id as \"assignmentId\", a.user_id as \"userId\", u.display_name as \"displayName\", a.role_code as \"roleCode\", r.role_name as \"roleName\", a.assignment_type as \"assignmentType\", a.approved_by_user_id as \"approvedByUserId\", au.display_name as \"approvedByName\", a.effective_start_date as \"effectiveStartDate\", a.effective_end_date as \"effectiveEndDate\", a.status").FROM("user_role_assignment a join app_user u on u.user_id=a.user_id join role r on r.role_code=a.role_code left join app_user au on au.user_id=a.approved_by_user_id"); addEq(sql,p,"userId","a.user_id"); addEq(sql,p,"roleCode","a.role_code"); addEq(sql,p,"status","a.status"); sql.ORDER_BY("u.display_name, a.role_code"); return sql.toString(); }
  public String listMenuPermissions(Map<String, Object> p) { SQL sql = new SQL().SELECT("p.permission_id as \"permissionId\", p.target_type as \"targetType\", p.target_id as \"targetId\", p.menu_id as \"menuId\", m.menu_name as \"menuName\", p.permission_level as \"permissionLevel\", p.is_active as \"isActive\"").FROM("menu_permission p join menu m on m.menu_id=p.menu_id"); addEq(sql,p,"targetType","p.target_type"); addEq(sql,p,"targetId","p.target_id"); addEq(sql,p,"menuId","p.menu_id"); sql.ORDER_BY("p.target_type, p.target_id, m.display_order"); return sql.toString(); }
  public String listMenus(Map<String, Object> p) { SQL sql = base("menu", "menu_id as \"menuId\", parent_menu_id as \"parentMenuId\", menu_name as \"menuName\", screen_id as \"screenId\", route_path as \"routePath\", icon_name as \"iconName\", business_category as \"businessCategory\", description, display_order as \"displayOrder\", is_active as \"isActive\""); addLike(sql,p,"menuName","menu_name"); addEq(sql,p,"businessCategory","business_category"); addEq(sql,p,"isActive","is_active"); sql.ORDER_BY("display_order, menu_id"); return sql.toString(); }
  public String listCodeGroups(Map<String, Object> p) { SQL sql = base("code_group", "group_id as \"groupId\", group_name as \"groupName\", description, managing_department as \"managingDepartment\", is_active as \"isActive\""); addLike(sql,p,"groupName","group_name"); addEq(sql,p,"isActive","is_active"); addGenericFilter(sql,p,"group_id","group_name","description","managing_department"); sql.ORDER_BY("group_id"); return sql.toString(); }
  public String listCodeDetails(Map<String, Object> p) { SQL sql = base("code_detail", "code_id as \"codeId\", group_id as \"groupId\", code_value as \"codeValue\", code_name as \"codeName\", parent_code_id as \"parentCodeId\", display_order as \"displayOrder\", extra_attributes as \"extraAttributes\", effective_start_date as \"effectiveStartDate\", effective_end_date as \"effectiveEndDate\", is_active as \"isActive\""); addEq(sql,p,"groupId","group_id"); addLike(sql,p,"codeName","code_name"); addEq(sql,p,"isActive","is_active"); addGenericFilter(sql,p,"code_value","code_name"); sql.ORDER_BY("group_id, display_order, code_value"); return sql.toString(); }
  private SQL base(String table, String select) { return new SQL().SELECT(select).FROM(table); }
  private boolean present(Map<String,Object> p, String key) { Object v=p.get(key); return v!=null && !String.valueOf(v).isBlank(); }
  private void addEq(SQL sql, Map<String,Object> p, String key, String column) { if (present(p,key)) sql.WHERE(column + "=#{" + key + "}"); }
  private void addLike(SQL sql, Map<String,Object> p, String key, String column) { if (present(p,key)) sql.WHERE(column + " ilike '%' || #{" + key + "} || '%'"); }
  private void addGenericFilter(SQL sql, Map<String,Object> p, String... columns) { if (!present(p,"filter")) return; StringBuilder b=new StringBuilder("("); for (int i=0;i<columns.length;i++){ if(i>0)b.append(" or "); b.append(columns[i]).append(" ilike '%' || #{filter} || '%'"); } b.append(")"); sql.WHERE(b.toString()); }
}
