package kr.ac.knue.facultyeval.system;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.*;

@Mapper
public interface AdminMapper {
  @SelectProvider(type=AdminSqlProvider.class, method="listUsers") List<Map<String,Object>> listUsers(Map<String,Object> params);
  @Select("select u.user_id as \"userId\", u.login_id as \"loginId\", u.staff_no as \"staffNo\", u.display_name as \"displayName\", u.org_code as \"orgCode\", o.org_name as \"orgName\", u.position_name as \"positionName\", u.employment_status as \"employmentStatus\", u.system_enabled as \"systemEnabled\", s.rank_name as \"rankName\", s.retirement_date as \"retirementDate\", s.last_synced_at as \"lastSyncedAt\" from app_user u left join organization o on o.org_code=u.org_code left join korus_staff_snapshot s on s.staff_no=u.staff_no where u.user_id=#{id}") Map<String,Object> getUser(String id);
  @Select("select role_code from user_role_assignment where user_id=#{userId} and status='ACTIVE' order by role_code") List<String> userRoleCodes(String userId);
  @Update("update app_user set system_enabled=#{systemEnabled}, updated_at=now() where user_id=#{userId}") int updateUserUsage(@Param("userId") String userId, @Param("systemEnabled") String systemEnabled);
  @Update("update user_role_assignment set status='REVOKED', effective_end_date=current_date, updated_at=now() where user_id=#{userId} and status='ACTIVE'") int revokeRolesForUser(String userId);
  @Insert("insert into user_role_assignment(assignment_id,user_id,role_code,assignment_type,approved_by_user_id,effective_start_date,effective_end_date,status,created_at,updated_at) values(#{assignmentId},#{userId},#{roleCode},#{assignmentType},#{approvedByUserId},#{effectiveStartDate}::date,#{effectiveEndDate}::date,'ACTIVE',now(),now())") int insertUserRole(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listOrganizations") List<Map<String,Object>> listOrganizations(Map<String,Object> params);
  @Update("update organization set parent_org_code=#{parentOrgCode}, effective_start_date=#{effectiveStartDate}::date, effective_end_date=#{effectiveEndDate}::date, updated_at=now() where org_code=#{orgCode}") int updateOrganizationRelationship(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listRoles") List<Map<String,Object>> listRoles(Map<String,Object> params);
  @Select("select role_code as \"roleCode\", role_name as \"roleName\", purpose, grant_criteria as \"grantCriteria\", default_data_scope as \"defaultDataScope\", is_active as \"isActive\" from role where role_code=#{roleCode}") Map<String,Object> getRole(String roleCode);
  @Insert("insert into role(role_code,role_name,purpose,grant_criteria,default_data_scope,is_active,created_at,updated_at) values(#{roleCode},#{roleName},#{purpose},#{grantCriteria},#{defaultDataScope},#{isActive},now(),now())") int insertRole(Map<String,Object> row);
  @Update("update role set role_name=#{roleName}, purpose=#{purpose}, grant_criteria=#{grantCriteria}, default_data_scope=#{defaultDataScope}, is_active=#{isActive}, updated_at=now() where role_code=#{roleCode}") int updateRole(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listUserRoles") List<Map<String,Object>> listUserRoles(Map<String,Object> params);
  @Update("update user_role_assignment set assignment_type=#{assignmentType}, approved_by_user_id=#{approvedByUserId}, effective_start_date=#{effectiveStartDate}::date, effective_end_date=#{effectiveEndDate}::date, status=#{status}, updated_at=now() where assignment_id=#{assignmentId}") int updateUserRole(Map<String,Object> row);
  @Update("update user_role_assignment set status='REVOKED', effective_end_date=current_date, updated_at=now() where assignment_id=#{assignmentId} and status='ACTIVE'") int revokeUserRole(String assignmentId);
  @SelectProvider(type=AdminSqlProvider.class, method="listMenuPermissions") List<Map<String,Object>> listMenuPermissions(Map<String,Object> params);
  @Delete("delete from menu_permission where target_type=#{targetType} and target_id=#{targetId}") int deleteMenuPermissions(Map<String,Object> row);
  @Insert("insert into menu_permission(permission_id,target_type,target_id,menu_id,permission_level,is_active,created_at,updated_at) values(#{permissionId},#{targetType},#{targetId},#{menuId},#{permissionLevel},'Y',now(),now())") int insertMenuPermission(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listMenus") List<Map<String,Object>> listMenus(Map<String,Object> params);
  @Select("select menu_id as \"menuId\", parent_menu_id as \"parentMenuId\", menu_name as \"menuName\", screen_id as \"screenId\", route_path as \"routePath\", icon_name as \"iconName\", business_category as \"businessCategory\", description, display_order as \"displayOrder\", is_active as \"isActive\" from menu where menu_id=#{menuId}") Map<String,Object> getMenu(String menuId);
  @Insert("insert into menu(menu_id,parent_menu_id,menu_name,screen_id,route_path,icon_name,business_category,description,display_order,is_active,created_at,updated_at) values(#{menuId},#{parentMenuId},#{menuName},#{screenId},#{routePath},#{iconName},#{businessCategory},#{description},#{displayOrder},#{isActive},now(),now())") int insertMenu(Map<String,Object> row);
  @Update("update menu set parent_menu_id=#{parentMenuId}, menu_name=#{menuName}, screen_id=#{screenId}, route_path=#{routePath}, icon_name=#{iconName}, business_category=#{businessCategory}, description=#{description}, display_order=#{displayOrder}, is_active=#{isActive}, updated_at=now() where menu_id=#{menuId}") int updateMenu(Map<String,Object> row);
  @Update("update menu set parent_menu_id=#{parentMenuId}, updated_at=now() where menu_id=#{menuId}") int updateMenuParent(Map<String,Object> row);
  @Update("update menu set display_order=#{displayOrder}, updated_at=now() where menu_id=#{menuId}") int updateMenuOrder(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listCodeGroups") List<Map<String,Object>> listCodeGroups(Map<String,Object> params);
  @Select("select group_id as \"groupId\", group_name as \"groupName\", description, managing_department as \"managingDepartment\", is_active as \"isActive\" from code_group where group_id=#{groupId}") Map<String,Object> getCodeGroup(String groupId);
  @Insert("insert into code_group(group_id,group_name,description,managing_department,is_active,created_at,updated_at) values(#{groupId},#{groupName},#{description},#{managingDepartment},#{isActive},now(),now())") int insertCodeGroup(Map<String,Object> row);
  @Update("update code_group set group_name=#{groupName}, description=#{description}, managing_department=#{managingDepartment}, is_active=#{isActive}, updated_at=now() where group_id=#{groupId}") int updateCodeGroup(Map<String,Object> row);
  @SelectProvider(type=AdminSqlProvider.class, method="listCodeDetails") List<Map<String,Object>> listCodeDetails(Map<String,Object> params);
  @Select("select code_id as \"codeId\", group_id as \"groupId\", code_value as \"codeValue\", code_name as \"codeName\", parent_code_id as \"parentCodeId\", display_order as \"displayOrder\", extra_attributes as \"extraAttributes\", effective_start_date as \"effectiveStartDate\", effective_end_date as \"effectiveEndDate\", is_active as \"isActive\" from code_detail where code_id=#{codeId}") Map<String,Object> getCodeDetail(String codeId);
  @Insert("insert into code_detail(code_id,group_id,code_value,code_name,parent_code_id,display_order,extra_attributes,effective_start_date,effective_end_date,is_active,created_at,updated_at) values(#{codeId},#{groupId},#{codeValue},#{codeName},#{parentCodeId},#{displayOrder},cast(#{extraAttributes} as jsonb),#{effectiveStartDate}::date,#{effectiveEndDate}::date,#{isActive},now(),now())") int insertCodeDetail(Map<String,Object> row);
  @Update("update code_detail set group_id=#{groupId}, code_value=#{codeValue}, code_name=#{codeName}, parent_code_id=#{parentCodeId}, display_order=#{displayOrder}, extra_attributes=cast(#{extraAttributes} as jsonb), effective_start_date=#{effectiveStartDate}::date, effective_end_date=#{effectiveEndDate}::date, is_active=#{isActive}, updated_at=now() where code_id=#{codeId}") int updateCodeDetail(Map<String,Object> row);
  @Insert("insert into change_history(history_id,entity_name,entity_id,operation_type,before_value,after_value,reason,processed_by_user_id,processed_at,created_at) values(#{historyId},#{entityName},#{entityId},#{operationType},cast(#{beforeValue} as jsonb),cast(#{afterValue} as jsonb),#{reason},#{processedByUserId},now(),now())") int insertHistory(Map<String,Object> row);
}
