package kr.ac.knue.facultyeval.system;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDate;
import java.util.*;
import kr.ac.knue.facultyeval.common.BusinessException;
import kr.ac.knue.facultyeval.common.PageResponse;
import kr.ac.knue.facultyeval.security.CurrentUserHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AdminService {
  private static final Set<String> ROLES = Set.of("R01","R02","R03","R04","R05","R06","R07","R08","R09");
  private final AdminMapper mapper;
  private final ObjectMapper objectMapper;

  public AdminService(AdminMapper mapper, ObjectMapper objectMapper) { this.mapper = mapper; this.objectMapper = objectMapper; }
  public PageResponse<Map<String,Object>> page(List<Map<String,Object>> items, Map<String,Object> p) { return new PageResponse<>(items, intParam(p,"page",0), intParam(p,"size",20), items.size()); }
  public PageResponse<Map<String,Object>> users(Map<String,Object> p) { return page(mapper.listUsers(p), p); }
  public Map<String,Object> user(String id) { Map<String,Object> user = mapper.getUser(id); notFound(user, "사용자"); user.put("roleCodes", mapper.userRoleCodes(id)); return user; }
  @Transactional public Map<String,Object> updateUserUsage(String id, Map<String,Object> body) { requireYn(body.get("systemEnabled"), "systemEnabled"); Map<String,Object> before=user(id); mapper.updateUserUsage(id, String.valueOf(body.get("systemEnabled"))); history("app_user", id, "UPDATE", before, user(id), reason(body)); return user(id); }
  @Transactional public Map<String,Object> replaceUserRoles(String id, Map<String,Object> body) { Object roles=body.get("roleCodes"); if (!(roles instanceof List<?>)) bad("roleCodes", "하나 이상의 역할이 필요합니다."); List<?> list=(List<?>)roles; if(list.isEmpty()) bad("roleCodes", "하나 이상의 역할이 필요합니다."); for(Object r:list) requireRole(String.valueOf(r)); Map<String,Object> before=user(id); mapper.revokeRolesForUser(id); for(Object r:list){ Map<String,Object> row = new HashMap<>(); row.put("assignmentId", UUID.randomUUID().toString()); row.put("userId", id); row.put("roleCode", String.valueOf(r)); row.put("assignmentType", "MANUAL"); row.put("approvedByUserId", actor()); row.put("effectiveStartDate", LocalDate.now().toString()); row.put("effectiveEndDate", null); mapper.insertUserRole(row); } history("user_role_assignment", id, "UPDATE", before, user(id), reason(body)); return user(id); }
  public PageResponse<Map<String,Object>> organizations(Map<String,Object> p) { return page(mapper.listOrganizations(p), p); }
  public Map<String,Object> organizationTree() { return Map.of("items", tree(mapper.listOrganizations(new HashMap<>()), "orgCode", "parentOrgCode")); }
  @Transactional public Map<String,Object> updateOrganizationRelationship(String orgCode, Map<String,Object> body) { validatePeriod(body); if (orgCode.equals(body.get("parentOrgCode"))) bad("parentOrgCode", "자기 자신을 상위조직으로 지정할 수 없습니다."); Map<String,Object> before = findByKey(mapper.listOrganizations(Map.of("orgCode", orgCode)), "orgCode", orgCode); body.put("orgCode", orgCode); mapper.updateOrganizationRelationship(body); Map<String,Object> after = findByKey(mapper.listOrganizations(Map.of("orgCode", orgCode)), "orgCode", orgCode); history("organization", orgCode, "UPDATE", before, after, reason(body)); return after; }
  public PageResponse<Map<String,Object>> roles(Map<String,Object> p) { return page(mapper.listRoles(p), p); }
  @Transactional public Map<String,Object> createRole(Map<String,Object> body) { validateRole(body); body.putIfAbsent("isActive", "Y"); mapper.insertRole(body); Map<String,Object> after=mapper.getRole(String.valueOf(body.get("roleCode"))); history("role", String.valueOf(body.get("roleCode")), "CREATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> updateRole(String code, Map<String,Object> body) { if (!code.equals(body.get("roleCode"))) throw new BusinessException(400,"ROLE_CODE_IMMUTABLE","roleCode는 path와 동일해야 합니다.", Map.of("roleCode","역할코드는 변경할 수 없습니다.")); validateRole(body); Map<String,Object> before=mapper.getRole(code); mapper.updateRole(body); Map<String,Object> after=mapper.getRole(code); history("role", code, "UPDATE", before, after, reason(body)); return after; }
  public PageResponse<Map<String,Object>> userRoles(Map<String,Object> p) { return page(mapper.listUserRoles(p), p); }
  @Transactional public Map<String,Object> createUserRole(Map<String,Object> body) { validateRoleAssignment(body); body.put("assignmentId", UUID.randomUUID().toString()); body.putIfAbsent("assignmentType", "MANUAL"); body.putIfAbsent("status", "ACTIVE"); mapper.insertUserRole(body); history("user_role_assignment", String.valueOf(body.get("assignmentId")), "CREATE", null, body, reason(body)); return body; }
  @Transactional public Map<String,Object> updateUserRole(String id, Map<String,Object> body) { validateRoleAssignment(body); body.put("assignmentId", id); body.putIfAbsent("status", "ACTIVE"); mapper.updateUserRole(body); history("user_role_assignment", id, "UPDATE", null, body, reason(body)); return body; }
  @Transactional public Map<String,Object> revokeUserRole(String id) { mapper.revokeUserRole(id); Map<String,Object> after=Map.of("assignmentId", id, "status", "REVOKED"); history("user_role_assignment", id, "REVOKE", null, after, "역할 회수"); return after; }
  public PageResponse<Map<String,Object>> menuPermissions(Map<String,Object> p) { return page(mapper.listMenuPermissions(p), p); }
  @Transactional public PageResponse<Map<String,Object>> saveMenuPermissions(Map<String,Object> body) { String targetType=String.valueOf(body.get("targetType")); if(!Set.of("ROLE","ORGANIZATION","USER").contains(targetType)) bad("targetType","ROLE/ORGANIZATION/USER 중 하나여야 합니다."); String targetId=required(body,"targetId"); mapper.deleteMenuPermissions(body); Object permissions=body.get("permissions"); if(!(permissions instanceof List<?>)) bad("permissions","권한 목록이 필요합니다."); List<?> list=(List<?>)permissions; for(Object item:list){ Map<String,Object> row=new HashMap<>((Map<String,Object>)item); row.put("permissionId", UUID.randomUUID().toString()); row.put("targetType", targetType); row.put("targetId", targetId); mapper.insertMenuPermission(row); } history("menu_permission", targetType+":"+targetId, "UPDATE", null, body, reason(body)); return menuPermissions(Map.of("targetType",targetType,"targetId",targetId)); }
  public Map<String,Object> menuTree() { return Map.of("items", tree(mapper.listMenus(new HashMap<>()), "menuId", "parentMenuId")); }
  public PageResponse<Map<String,Object>> menus(Map<String,Object> p) { return page(mapper.listMenus(p), p); }
  public Map<String,Object> menu(String id) { Map<String,Object> m=mapper.getMenu(id); notFound(m,"메뉴"); return m; }
  @Transactional public Map<String,Object> createMenu(Map<String,Object> body) { requireText(body,"menuName"); requireText(body,"routePath"); requireText(body,"businessCategory"); body.putIfAbsent("menuId", UUID.randomUUID().toString()); body.putIfAbsent("displayOrder", 99); body.putIfAbsent("isActive", "Y"); mapper.insertMenu(body); Map<String,Object> after=menu(String.valueOf(body.get("menuId"))); history("menu", String.valueOf(body.get("menuId")), "CREATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> updateMenu(String id, Map<String,Object> body) { requireText(body,"menuName"); requireText(body,"routePath"); requireText(body,"businessCategory"); body.put("menuId", id); body.putIfAbsent("isActive", "Y"); mapper.updateMenu(body); Map<String,Object> after=menu(id); history("menu", id, "UPDATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> updateMenuParent(String id, Map<String,Object> body) { if(id.equals(body.get("parentMenuId"))) bad("parentMenuId","자기 자신을 부모로 지정할 수 없습니다."); body.put("menuId", id); mapper.updateMenuParent(body); Map<String,Object> after=menu(id); history("menu", id, "UPDATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> reorderMenus(Map<String,Object> body) { Object items=body.get("items"); if(!(items instanceof List<?>)) bad("items","재정렬 목록이 필요합니다."); List<?> list=(List<?>)items; if(list.isEmpty()) bad("items","재정렬 목록이 필요합니다."); Set<Object> orders=new HashSet<>(); for(Object item:list){ Map<String,Object> row=(Map<String,Object>)item; if(!orders.add(row.get("displayOrder"))) bad("displayOrder","동일 계층 표시순서는 중복될 수 없습니다."); mapper.updateMenuOrder(row); } history("menu", "reorder", "REORDER", null, body, reason(body)); return menuTree(); }
  public PageResponse<Map<String,Object>> codeGroups(Map<String,Object> p) { return page(mapper.listCodeGroups(p), p); }
  public Map<String,Object> codeGroup(String id) { Map<String,Object> row=mapper.getCodeGroup(id); notFound(row,"코드그룹"); return row; }
  @Transactional public Map<String,Object> createCodeGroup(Map<String,Object> body) { requireText(body,"groupId"); requireText(body,"groupName"); body.putIfAbsent("isActive", "Y"); mapper.insertCodeGroup(body); Map<String,Object> after=codeGroup(String.valueOf(body.get("groupId"))); history("code_group", String.valueOf(body.get("groupId")), "CREATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> updateCodeGroup(String id, Map<String,Object> body) { requireText(body,"groupName"); body.put("groupId", id); body.putIfAbsent("isActive", "Y"); mapper.updateCodeGroup(body); Map<String,Object> after=codeGroup(id); history("code_group", id, "UPDATE", null, after, reason(body)); return after; }
  public PageResponse<Map<String,Object>> codeDetails(Map<String,Object> p) { return page(mapper.listCodeDetails(p), p); }
  public Map<String,Object> codeDetail(String id) { Map<String,Object> row=mapper.getCodeDetail(id); notFound(row,"상세코드"); return row; }
  @Transactional public Map<String,Object> createCodeDetail(Map<String,Object> body) { validateCodeDetail(body); body.putIfAbsent("codeId", UUID.randomUUID().toString()); mapper.insertCodeDetail(body); Map<String,Object> after=codeDetail(String.valueOf(body.get("codeId"))); history("code_detail", String.valueOf(body.get("codeId")), "CREATE", null, after, reason(body)); return after; }
  @Transactional public Map<String,Object> updateCodeDetail(String id, Map<String,Object> body) { validateCodeDetail(body); body.put("codeId", id); mapper.updateCodeDetail(body); Map<String,Object> after=codeDetail(id); history("code_detail", id, "UPDATE", null, after, reason(body)); return after; }
  private void validateRole(Map<String,Object> b){ requireRole(String.valueOf(b.get("roleCode"))); requireText(b,"roleName"); requireText(b,"purpose"); if(!Set.of("SELF","ORG","ALL").contains(String.valueOf(b.get("defaultDataScope")))) bad("defaultDataScope","SELF/ORG/ALL 중 하나여야 합니다."); b.putIfAbsent("isActive","Y"); requireYn(b.get("isActive"),"isActive"); }
  private void validateRoleAssignment(Map<String,Object> b){ requireText(b,"userId"); requireRole(String.valueOf(b.get("roleCode"))); validatePeriod(b); requireText(b,"approvedByUserId"); }
  private void validateCodeDetail(Map<String,Object> b){ requireText(b,"groupId"); requireText(b,"codeValue"); requireText(b,"codeName"); b.putIfAbsent("extraAttributes","{}"); b.putIfAbsent("isActive","Y"); requireYn(b.get("isActive"),"isActive"); validatePeriod(b); }
  private void validatePeriod(Map<String,Object> b){ requireText(b,"effectiveStartDate"); Object end=b.get("effectiveEndDate"); if(end!=null && !String.valueOf(end).isBlank() && LocalDate.parse(String.valueOf(end)).isBefore(LocalDate.parse(String.valueOf(b.get("effectiveStartDate"))))) bad("effectiveEndDate","종료일은 시작일보다 빠를 수 없습니다."); }
  private void history(String entity, String id, String op, Object before, Object after, String reason){ try { Map<String,Object> row=new HashMap<>(); row.put("historyId", UUID.randomUUID().toString()); row.put("entityName", entity); row.put("entityId", id); row.put("operationType", op); row.put("beforeValue", before==null?null:objectMapper.writeValueAsString(before)); row.put("afterValue", after==null?null:objectMapper.writeValueAsString(after)); row.put("reason", reason); row.put("processedByUserId", actor()); mapper.insertHistory(row); } catch(Exception ex) { throw new BusinessException(500,"HISTORY_FAILED","변경 이력 기록에 실패했습니다."); } }
  private String actor(){ return CurrentUserHolder.get()==null ? "admin" : CurrentUserHolder.get().userId(); }
  private String reason(Map<String,Object> b){ Object r=b.get("reason"); return r==null||String.valueOf(r).isBlank()?"관리 화면 처리":String.valueOf(r); }
  private void requireRole(String r){ if(!ROLES.contains(r)) bad("roleCode","R01~R09 중 하나여야 합니다."); }
  private void requireYn(Object v,String f){ if(!Set.of("Y","N").contains(String.valueOf(v))) bad(f,"Y/N 중 하나여야 합니다."); }
  private void requireText(Map<String,Object>b,String f){ if(!b.containsKey(f)||b.get(f)==null||String.valueOf(b.get(f)).isBlank()) bad(f,"필수값입니다."); }
  private String required(Map<String,Object>b,String f){ requireText(b,f); return String.valueOf(b.get(f)); }
  private void bad(String f,String m){ throw new BusinessException(400,"VALIDATION_ERROR","입력값을 확인해 주세요.",Map.of(f,m)); }
  private void notFound(Object o,String label){ if(o==null) throw new BusinessException(404,"NOT_FOUND",label+"을 찾을 수 없습니다."); }
  private int intParam(Map<String,Object> p,String key,int d){ Object v=p.get(key); return v==null?d:Integer.parseInt(String.valueOf(v)); }
  private Map<String,Object> findByKey(List<Map<String,Object>> rows,String key,String value){ return rows.stream().filter(r -> value.equals(String.valueOf(r.get(key)))).findFirst().orElseThrow(() -> new BusinessException(404,"NOT_FOUND","대상을 찾을 수 없습니다.")); }
  private List<Map<String,Object>> tree(List<Map<String,Object>> rows,String idKey,String parentKey){ Map<String,List<Map<String,Object>>> byParent=new LinkedHashMap<>(); for(Map<String,Object> row:rows){ row.put("children", new ArrayList<>()); String parent=String.valueOf(row.get(parentKey)); if(row.get(parentKey)==null) parent=""; byParent.computeIfAbsent(parent,k->new ArrayList<>()).add(row); } for(Map<String,Object> row:rows){ List<Map<String,Object>> children=byParent.get(String.valueOf(row.get(idKey))); if(children!=null) row.put("children", children); } return byParent.getOrDefault("", new ArrayList<>()); }
}
