package kr.ac.knue.fpe.admin;

import org.apache.ibatis.annotations.*;
import java.util.*;

@Mapper
public interface AdminMapper {
    @SelectProvider(type=AdminSqlProvider.class, method="listUsers") List<Map<String,Object>> listUsers(Map<String,Object> p);
    @Update("update user_account set system_use_yn=#{systemUseYn}, account_status=#{accountStatus}, updated_at=now() where user_id=#{userId}") int updateUserUsage(Map<String,Object> p);
    @Select("select ua.user_id, ua.employee_no, ua.login_id, ua.display_name, ks.organization_code, o.organization_name, ks.job_grade, ks.employment_status, ks.position_name, ks.retirement_date, ks.last_synced_at, ua.system_use_yn, ua.account_status from user_account ua left join korus_personnel_snapshot ks on ks.employee_no=ua.employee_no left join organization o on o.organization_code=ks.organization_code where ua.user_id=#{userId}") Map<String,Object> userById(@Param("userId") String userId);
    @SelectProvider(type=AdminSqlProvider.class, method="listOrganizations") List<Map<String,Object>> listOrganizations(Map<String,Object> p);
    @Select("select organization_id, organization_code, organization_name, organization_type, parent_organization_code, effective_start_date, effective_end_date, use_yn from organization where use_yn='Y' order by parent_organization_code nulls first, organization_code") List<Map<String,Object>> organizationTreeRows();
    @Update("update organization set parent_organization_code=#{parentOrganizationCode}, effective_start_date=cast(#{effectiveStartDate} as date), effective_end_date=cast(#{effectiveEndDate} as date), updated_at=now() where organization_code=#{organizationCode}") int updateOrganizationRelation(Map<String,Object> p);
    @Select("select organization_id, organization_code, organization_name, organization_type, parent_organization_code, effective_start_date, effective_end_date, use_yn from organization where organization_code=#{organizationCode}") Map<String,Object> organizationByCode(@Param("organizationCode") String organizationCode);
    @SelectProvider(type=AdminSqlProvider.class, method="listRoles") List<Map<String,Object>> listRoles(Map<String,Object> p);
    @Insert("insert into role(role_code,role_name,role_purpose,assignment_criteria,default_data_scope,use_yn,created_at,updated_at) values(#{roleCode},#{roleName},#{rolePurpose},#{assignmentCriteria},#{defaultDataScope},#{useYn},now(),now())") int createRole(Map<String,Object> p);
    @Update("update role set role_name=#{roleName}, role_purpose=#{rolePurpose}, assignment_criteria=#{assignmentCriteria}, default_data_scope=#{defaultDataScope}, use_yn=#{useYn}, updated_at=now() where role_code=#{roleCode}") int updateRole(Map<String,Object> p);
    @Select("select role_code, role_name, role_purpose, assignment_criteria, default_data_scope, use_yn from role where role_code=#{roleCode}") Map<String,Object> roleByCode(@Param("roleCode") String roleCode);
    @SelectProvider(type=AdminSqlProvider.class, method="listUserRoles") List<Map<String,Object>> listUserRoles(Map<String,Object> p);
    @Insert("insert into user_role(user_role_id,user_id,role_code,role_source,valid_from,valid_to,approved_by_user_id,assignment_status,created_at,updated_at) values(cast(#{userRoleId} as uuid),cast(#{userId} as uuid),#{roleCode},#{roleSource},cast(#{validFrom} as date),cast(#{validTo} as date),cast(#{approvedByUserId} as uuid),'ACTIVE',now(),now())") int assignUserRole(Map<String,Object> p);
    @Update("update user_role set assignment_status='REVOKED', updated_at=now() where user_role_id=cast(#{userRoleId} as uuid) and assignment_status='ACTIVE'") int revokeUserRole(Map<String,Object> p);
    @Select("select user_role_id, user_id, role_code, role_source, valid_from, valid_to, approved_by_user_id, assignment_status from user_role where user_role_id=cast(#{userRoleId} as uuid)") Map<String,Object> userRoleById(@Param("userRoleId") String userRoleId);
    @SelectProvider(type=AdminSqlProvider.class, method="listMenus") List<Map<String,Object>> listMenus(Map<String,Object> p);
    @Select("select menu_id, parent_menu_id, menu_level, display_order, menu_name, screen_id, url_path, icon_name, business_category, description, use_yn, 'Y' as access_allowed_yn from menu where use_yn='Y' order by parent_menu_id nulls first, display_order") List<Map<String,Object>> menuTreeRows();
    @Insert("insert into menu(menu_id,parent_menu_id,menu_level,display_order,menu_name,screen_id,url_path,icon_name,business_category,description,use_yn,created_at,updated_at) values(cast(#{menuId} as uuid),cast(#{parentMenuId} as uuid),#{menuLevel},#{displayOrder},#{menuName},#{screenId},#{urlPath},#{iconName},#{businessCategory},#{description},#{useYn},now(),now())") int createMenu(Map<String,Object> p);
    @Update("update menu set parent_menu_id=cast(#{parentMenuId} as uuid), menu_level=#{menuLevel}, display_order=#{displayOrder}, menu_name=#{menuName}, screen_id=#{screenId}, url_path=#{urlPath}, icon_name=#{iconName}, business_category=#{businessCategory}, description=#{description}, use_yn=#{useYn}, updated_at=now() where menu_id=cast(#{menuId} as uuid)") int updateMenu(Map<String,Object> p);
    @Update("update menu set display_order=#{displayOrder}, updated_at=now() where menu_id=cast(#{menuId} as uuid)") int updateMenuOrder(Map<String,Object> p);
    @Select("select menu_id, parent_menu_id, menu_level, display_order, menu_name, screen_id, url_path, icon_name, business_category, description, use_yn from menu where menu_id=cast(#{menuId} as uuid)") Map<String,Object> menuById(@Param("menuId") String menuId);
    @Select("select menu_permission_id, target_type, target_id, menu_id, access_allowed_yn from menu_permission where target_type=#{targetType} and target_id=#{targetId} order by menu_id limit #{size} offset #{offset}") List<Map<String,Object>> listMenuPermissions(Map<String,Object> p);
    @Delete("delete from menu_permission where target_type=#{targetType} and target_id=#{targetId}") int deletePermissions(Map<String,Object> p);
    @Insert("insert into menu_permission(menu_permission_id,target_type,target_id,menu_id,access_allowed_yn,created_at,updated_at) values(gen_random_uuid(),#{targetType},#{targetId},cast(#{menuId} as uuid),#{accessAllowedYn},now(),now())") int insertPermission(Map<String,Object> p);
    @SelectProvider(type=AdminSqlProvider.class, method="listCodeGroups") List<Map<String,Object>> listCodeGroups(Map<String,Object> p);
    @Insert("insert into code_group(group_id,group_name,description,managing_department,use_yn,created_at,updated_at) values(#{groupId},#{groupName},#{description},#{managingDepartment},#{useYn},now(),now())") int createCodeGroup(Map<String,Object> p);
    @Update("update code_group set group_name=#{groupName}, description=#{description}, managing_department=#{managingDepartment}, use_yn=#{useYn}, updated_at=now() where group_id=#{groupId}") int updateCodeGroup(Map<String,Object> p);
    @Select("select group_id, group_name, description, managing_department, use_yn from code_group where group_id=#{groupId}") Map<String,Object> codeGroupById(@Param("groupId") String groupId);
    @SelectProvider(type=AdminSqlProvider.class, method="listDetailCodes") List<Map<String,Object>> listDetailCodes(Map<String,Object> p);
    @Insert("insert into detail_code(detail_code_id,group_id,code_value,code_name,parent_detail_code_id,sort_order,additional_attributes,use_yn,valid_from,valid_to,created_at,updated_at) values(cast(#{detailCodeId} as uuid),#{groupId},#{codeValue},#{codeName},cast(#{parentDetailCodeId} as uuid),#{sortOrder},cast(#{additionalAttributes} as jsonb),#{useYn},cast(#{validFrom} as date),cast(#{validTo} as date),now(),now())") int createDetailCode(Map<String,Object> p);
    @Update("update detail_code set code_name=#{codeName}, parent_detail_code_id=cast(#{parentDetailCodeId} as uuid), sort_order=#{sortOrder}, additional_attributes=cast(#{additionalAttributes} as jsonb), use_yn=#{useYn}, valid_from=cast(#{validFrom} as date), valid_to=cast(#{validTo} as date), updated_at=now() where detail_code_id=cast(#{detailCodeId} as uuid)") int updateDetailCode(Map<String,Object> p);
    @Select("select detail_code_id, group_id, code_value, code_name, parent_detail_code_id, sort_order, additional_attributes, use_yn, valid_from, valid_to from detail_code where detail_code_id=cast(#{detailCodeId} as uuid)") Map<String,Object> detailCodeById(@Param("detailCodeId") String detailCodeId);
}
