export type FieldType = "text" | "textarea" | "select" | "date" | "number";

export type ScreenField = {
  key: string;
  label: string;
  type?: FieldType;
  readonly?: boolean;
  options?: string[];
  placeholder?: string;
  helper?: string;
};

export type ScreenAction = {
  label: string;
  kind:
    | "create"
    | "edit"
    | "save"
    | "readonly"
    | "logicalDelete"
    | "terminate"
    | "local"
    | "navigate";
  description: string;
};

export type ScreenConfig = {
  id: string;
  route: string;
  title: string;
  apiPath: string;
  menuPath: string;
  topMenu: string;
  middleMenu: string;
  entity: string;
  archetype: string;
  goal: string;
  primaryCta: string;
  readonlyNotice?: string;
  oqNotice?: string;
  columns: ScreenField[];
  editableFields: ScreenField[];
  readonlyFields?: ScreenField[];
  searchFields: ScreenField[];
  actions: ScreenAction[];
  supportsCreate?: boolean;
  noMutation?: boolean;
  secondaryApis?: { label: string; path: string }[];
};

const ynOptions = ["Y", "N"];
const statusOptions = [
  "ACTIVE",
  "INACTIVE",
  "PENDING",
  "RUNNING",
  "COMPLETED",
  "FAILED",
  "TERMINATED",
  "REVOKED",
  "EXPIRED",
  "STOPPED",
];
const baseColumns: ScreenField[] = [
  { key: "id", label: "식별자", readonly: true },
  { key: "title", label: "명칭" },
  { key: "status", label: "상태", type: "select", options: statusOptions },
  { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
  { key: "updatedAt", label: "수정일시", readonly: true },
];
const baseSearch: ScreenField[] = [
  {
    key: "keyword",
    label: "통합 검색어",
    placeholder: "식별자, 명칭, payload 필드 검색",
  },
];
const baseEdit: ScreenField[] = [
  {
    key: "id",
    label: "식별자",
    helper: "기존 레코드에서는 변경할 수 없습니다.",
  },
  { key: "title", label: "명칭" },
  { key: "status", label: "상태", type: "select", options: statusOptions },
  { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
];

function screen(
  config: Omit<
    ScreenConfig,
    "columns" | "editableFields" | "searchFields" | "actions"
  > & {
    columns?: ScreenField[];
    editableFields?: ScreenField[];
    readonlyFields?: ScreenField[];
    searchFields?: ScreenField[];
    actions?: ScreenAction[];
  },
): ScreenConfig {
  return {
    columns: config.columns ?? baseColumns,
    editableFields: config.editableFields ?? baseEdit,
    readonlyFields: config.readonlyFields,
    searchFields: config.searchFields ?? baseSearch,
    actions: config.actions ?? [
      {
        label: "검색",
        kind: "local",
        description: `${config.apiPath} GET 목록 조회`,
      },
      {
        label: "신규 등록",
        kind: "create",
        description: `${config.apiPath} POST 신규 저장`,
      },
      {
        label: "수정",
        kind: "edit",
        description: `${config.apiPath} POST 변경 저장`,
      },
    ],
    ...config,
  };
}

export const screens = [
  screen({
    id: "SCR-001-users",
    route: "/admin/users",
    title: "사용자 관리",
    apiPath: "/api/users",
    menuPath: "시스템 관리 > 사용자·조직 관리 > 사용자 관리",
    topMenu: "시스템 관리",
    middleMenu: "사용자·조직 관리",
    entity: "users",
    archetype: "search/list/detail",
    goal: "KORUS 원천 인사정보를 확인하고 시스템 사용여부와 업무 역할만 변경합니다.",
    primaryCta: "사용자 저장",
    readonlyNotice:
      "KORUS 원천 인사정보는 읽기 전용이며 저장 payload에 원천 필드 변경을 포함하지 않습니다.",
    supportsCreate: false,
    columns: [
      { key: "id", label: "교번", readonly: true },
      { key: "employeeNo", label: "교번", readonly: true },
      { key: "title", label: "성명" },
      { key: "organizationCode", label: "소속", readonly: true },
      { key: "rankName", label: "직급", readonly: true },
      { key: "employmentStatus", label: "재직상태", readonly: true },
      { key: "primaryRoleCode", label: "역할" },
      {
        key: "systemUseYn",
        label: "사용여부",
        type: "select",
        options: ynOptions,
      },
      { key: "position", label: "보직", readonly: true },
      { key: "retirementDate", label: "퇴직일자", readonly: true },
      { key: "lastSyncedAt", label: "최종 동기화일시", readonly: true },
    ],
    searchFields: [
      {
        key: "keyword",
        label: "교번·성명·소속·직급·역할",
        placeholder: "사용자 검색어",
      },
      {
        key: "systemUseYn",
        label: "사용여부",
        type: "select",
        options: ["", ...ynOptions],
      },
    ],
    readonlyFields: [
      { key: "employeeNo", label: "교번" },
      { key: "title", label: "성명" },
      { key: "organizationCode", label: "소속" },
      { key: "rankName", label: "직급" },
      { key: "employmentStatus", label: "재직상태" },
      { key: "position", label: "보직" },
      { key: "retirementDate", label: "퇴직일자" },
      { key: "lastSyncedAt", label: "최종 동기화일시" },
    ],
    editableFields: [
      { key: "id", label: "사용자 식별자" },
      {
        key: "systemUseYn",
        label: "시스템 사용여부",
        type: "select",
        options: ynOptions,
      },
      {
        key: "primaryRoleCode",
        label: "업무 역할",
        placeholder: "role API/DB 기준 role_code",
      },
    ],
  }),
  screen({
    id: "SCR-002-organizations",
    route: "/admin/organizations",
    title: "조직 관리",
    apiPath: "/api/organizations",
    menuPath: "시스템 관리 > 사용자·조직 관리 > 조직 관리",
    topMenu: "시스템 관리",
    middleMenu: "사용자·조직 관리",
    entity: "organizations",
    archetype: "tree editor",
    goal: "조직 계층을 조회하고 상위조직 관계와 적용기간 변경 이력을 관리합니다.",
    primaryCta: "조직 관계 저장",
    supportsCreate: false,
    columns: [
      { key: "id", label: "조직코드" },
      { key: "title", label: "조직명" },
      { key: "organizationType", label: "조직유형" },
      { key: "parentOrganizationCode", label: "상위조직코드" },
      { key: "effectiveStartDate", label: "적용 시작일" },
      { key: "effectiveEndDate", label: "적용 종료일" },
      { key: "status", label: "상태" },
    ],
    editableFields: [
      { key: "id", label: "조직코드" },
      { key: "title", label: "조직명" },
      {
        key: "organizationType",
        label: "조직유형",
        type: "select",
        options: ["대학", "대학원", "단과대학", "학과", "부서"],
      },
      { key: "parentOrganizationCode", label: "상위조직코드" },
      { key: "effectiveStartDate", label: "적용 시작일", type: "date" },
      { key: "effectiveEndDate", label: "적용 종료일", type: "date" },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-003-positions",
    route: "/admin/positions",
    title: "보직 관리",
    apiPath: "/api/positions",
    menuPath: "시스템 관리 > 사용자·조직 관리 > 보직 관리",
    topMenu: "시스템 관리",
    middleMenu: "사용자·조직 관리",
    entity: "positions",
    archetype: "effective-period form",
    goal: "보직코드별 대상 사용자·조직·유효기간을 조회하고 모달에서 신규 등록 또는 수정합니다.",
    primaryCta: "보직 저장",
    columns: [
      { key: "id", label: "보직코드" },
      { key: "title", label: "보직명" },
      { key: "targetUserId", label: "대상 사용자" },
      { key: "organizationCode", label: "소속조직" },
      { key: "effectiveStartDate", label: "유효 시작일" },
      { key: "effectiveEndDate", label: "유효 종료일" },
    ],
    editableFields: [
      { key: "id", label: "보직코드" },
      { key: "title", label: "보직명" },
      { key: "targetUserId", label: "대상 사용자" },
      { key: "organizationCode", label: "소속조직" },
      { key: "effectiveStartDate", label: "유효 시작일", type: "date" },
      { key: "effectiveEndDate", label: "유효 종료일", type: "date" },
    ],
  }),
  screen({
    id: "SCR-004-roles",
    route: "/admin/roles",
    title: "역할 관리",
    apiPath: "/api/roles",
    menuPath: "시스템 관리 > 역할·권한 관리 > 역할 관리",
    topMenu: "시스템 관리",
    middleMenu: "역할·권한 관리",
    entity: "roles",
    archetype: "search/list/detail",
    goal: "역할 목적·부여 기준·데이터 범위 기본값을 조회하고 역할명/목적을 관리합니다. R01~R09 역할코드는 고정 식별자입니다.",
    primaryCta: "역할 저장",
    columns: [
      { key: "id", label: "역할코드" },
      { key: "title", label: "역할명" },
      { key: "purpose", label: "역할 목적" },
      { key: "assignmentCriteria", label: "부여 기준" },
      { key: "defaultDataScope", label: "데이터 범위 기본값" },
    ],
    editableFields: [
      { key: "id", label: "역할코드" },
      { key: "title", label: "역할명" },
      { key: "purpose", label: "역할 목적", type: "textarea" },
      { key: "assignmentCriteria", label: "부여 기준", type: "textarea" },
      { key: "defaultDataScope", label: "데이터 범위 기본값" },
    ],
  }),
  screen({
    id: "SCR-005-user-roles",
    route: "/admin/user-roles",
    title: "사용자 역할 관리",
    apiPath: "/api/user-roles",
    menuPath: "시스템 관리 > 역할·권한 관리 > 사용자 역할 관리",
    topMenu: "시스템 관리",
    middleMenu: "역할·권한 관리",
    entity: "user_roles",
    archetype: "search/list/detail",
    goal: "사용자별 현재 역할과 유효기간을 조회하고 수동 역할 부여·변경·회수를 처리합니다.",
    primaryCta: "역할 부여 저장",
    columns: [
      { key: "id", label: "배정ID" },
      { key: "userId", label: "사용자" },
      { key: "roleCode", label: "역할코드" },
      { key: "assignmentType", label: "부여구분" },
      { key: "approverUserId", label: "승인자" },
      { key: "effectiveStartDate", label: "유효 시작일" },
      { key: "effectiveEndDate", label: "유효 종료일" },
      { key: "currentYn", label: "현재 적용" },
    ],
    editableFields: [
      { key: "id", label: "배정ID" },
      { key: "userId", label: "사용자" },
      { key: "roleCode", label: "역할코드" },
      {
        key: "assignmentType",
        label: "부여구분",
        type: "select",
        options: ["MANUAL", "POSITION_BASED", "REVOKE"],
      },
      { key: "approverUserId", label: "승인자" },
      { key: "effectiveStartDate", label: "유효 시작일", type: "date" },
      { key: "effectiveEndDate", label: "유효 종료일", type: "date" },
    ],
  }),
  screen({
    id: "SCR-006-menu-permissions",
    route: "/admin/menu-permissions",
    title: "메뉴 권한 관리",
    apiPath: "/api/menu-permissions",
    menuPath: "시스템 관리 > 역할·권한 관리 > 메뉴 권한 관리",
    topMenu: "시스템 관리",
    middleMenu: "역할·권한 관리",
    entity: "menu_permissions",
    archetype: "permission matrix",
    goal: "역할·조직·사용자별 메뉴 접근 허용 여부를 서버 접근통제와 메뉴 노출에 동일하게 적용합니다.",
    primaryCta: "메뉴 권한 저장",
    supportsCreate: false,
    columns: [
      { key: "id", label: "권한ID" },
      { key: "targetType", label: "대상 유형" },
      { key: "targetId", label: "대상" },
      { key: "menuPath", label: "메뉴 계층" },
      { key: "screenId", label: "화면" },
      { key: "allowedYn", label: "접근 허용" },
      { key: "reason", label: "사유" },
    ],
    editableFields: [
      { key: "id", label: "권한ID" },
      {
        key: "targetType",
        label: "대상 유형",
        type: "select",
        options: ["ROLE", "ORGANIZATION", "USER"],
      },
      { key: "targetId", label: "대상" },
      { key: "menuPath", label: "메뉴 계층" },
      { key: "screenId", label: "화면" },
      {
        key: "allowedYn",
        label: "접근 허용",
        type: "select",
        options: ynOptions,
      },
      { key: "reason", label: "사유", type: "textarea" },
    ],
  }),
  screen({
    id: "SCR-007-function-permissions",
    route: "/admin/function-permissions",
    title: "기능 권한 관리",
    apiPath: "/api/function-permissions",
    menuPath: "시스템 관리 > 역할·권한 관리 > 기능 권한 관리",
    topMenu: "시스템 관리",
    middleMenu: "역할·권한 관리",
    entity: "function_permissions",
    archetype: "permission matrix",
    goal: "역할과 화면 조합별 조회·등록·수정·삭제·출력·엑셀 등 기능 허용 여부를 관리합니다.",
    primaryCta: "기능 권한 저장",
    supportsCreate: false,
    columns: [
      { key: "id", label: "권한ID" },
      { key: "roleCode", label: "역할코드" },
      { key: "screenId", label: "화면" },
      { key: "functionType", label: "기능구분" },
      { key: "allowedYn", label: "허용 여부" },
      { key: "reason", label: "사유" },
      { key: "updatedAt", label: "수정일시" },
    ],
    editableFields: [
      { key: "id", label: "권한ID" },
      { key: "roleCode", label: "역할코드" },
      { key: "screenId", label: "화면" },
      {
        key: "functionType",
        label: "기능구분",
        type: "select",
        options: [
          "READ",
          "CREATE",
          "UPDATE",
          "DELETE",
          "CONFIRM",
          "AUTH",
          "APPROVE",
          "CANCEL_APPROVE",
          "PRINT",
          "EXCEL",
          "BATCH",
        ],
      },
      {
        key: "allowedYn",
        label: "허용 여부",
        type: "select",
        options: ynOptions,
      },
      { key: "reason", label: "사유", type: "textarea" },
    ],
  }),
  screen({
    id: "SCR-008-data-scope-permissions",
    route: "/admin/data-scope-permissions",
    title: "데이터 범위 권한",
    apiPath: "/api/data-scope-permissions",
    menuPath: "시스템 관리 > 역할·권한 관리 > 데이터 범위 권한",
    topMenu: "시스템 관리",
    middleMenu: "역할·권한 관리",
    entity: "data_scope_permissions",
    archetype: "permission matrix",
    goal: "역할별 데이터 범위 유형과 조직코드·업무영역 조건을 서버 조회조건으로 강제 적용합니다.",
    primaryCta: "데이터 범위 저장",
    supportsCreate: false,
    readonlyNotice:
      "데이터 범위는 화면 필터 대체물이 아니라 서버 조회조건으로 적용됩니다.",
    columns: [
      { key: "id", label: "권한ID" },
      { key: "roleCode", label: "역할코드" },
      { key: "scopeType", label: "범위 유형" },
      { key: "organizationCode", label: "조직코드" },
      { key: "businessArea", label: "업무영역" },
      { key: "useYn", label: "사용여부" },
      { key: "updatedAt", label: "수정일시" },
    ],
    editableFields: [
      { key: "id", label: "권한ID" },
      { key: "roleCode", label: "역할코드" },
      {
        key: "scopeType",
        label: "범위 유형",
        type: "select",
        options: ["SELF", "DEPARTMENT", "COLLEGE", "BUSINESS", "ALL"],
      },
      { key: "organizationCode", label: "조직코드" },
      { key: "businessArea", label: "업무영역" },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-009-menus",
    route: "/admin/menus",
    title: "메뉴 관리",
    apiPath: "/api/menus",
    menuPath: "시스템 관리 > 메뉴 관리 > 메뉴 관리",
    topMenu: "시스템 관리",
    middleMenu: "메뉴 관리",
    entity: "menus",
    archetype: "tree editor",
    goal: "대·중·소메뉴 계층과 실행 화면 연결 정보를 관리하고 같은 부모·계층 안의 표시순서를 조정합니다.",
    primaryCta: "메뉴 실행정보 저장",
    columns: [
      { key: "id", label: "메뉴ID" },
      { key: "parentMenuId", label: "부모메뉴" },
      { key: "displayOrder", label: "표시순서" },
      { key: "title", label: "메뉴명" },
      { key: "screenId", label: "화면ID" },
      { key: "url", label: "URL" },
      { key: "icon", label: "아이콘" },
      { key: "businessType", label: "업무구분" },
    ],
    editableFields: [
      { key: "id", label: "메뉴ID" },
      { key: "parentMenuId", label: "부모메뉴" },
      { key: "displayOrder", label: "표시순서", type: "number" },
      { key: "title", label: "메뉴명" },
      { key: "screenId", label: "화면ID" },
      { key: "url", label: "URL" },
      { key: "icon", label: "아이콘" },
      { key: "businessType", label: "업무구분" },
      { key: "description", label: "설명", type: "textarea" },
    ],
  }),
  screen({
    id: "SCR-010-code-groups",
    route: "/admin/code-groups",
    title: "코드그룹 관리",
    apiPath: "/api/code-groups",
    menuPath: "시스템 관리 > 공통코드 관리 > 코드그룹 관리",
    topMenu: "시스템 관리",
    middleMenu: "공통코드 관리",
    entity: "code_groups",
    archetype: "search/list/detail",
    goal: "코드그룹의 그룹ID·명칭·설명·관리부서를 관리하고 선택 그룹을 상세코드 화면으로 넘깁니다.",
    primaryCta: "코드그룹 저장",
    columns: [
      { key: "id", label: "그룹ID" },
      { key: "title", label: "명칭" },
      { key: "description", label: "설명" },
      { key: "managedDepartment", label: "관리부서" },
      { key: "useYn", label: "사용여부" },
      { key: "updatedAt", label: "수정일시" },
    ],
    editableFields: [
      { key: "id", label: "그룹ID" },
      { key: "title", label: "명칭" },
      { key: "description", label: "설명", type: "textarea" },
      { key: "managedDepartment", label: "관리부서" },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
    actions: [
      { label: "검색", kind: "local", description: "GET /api/code-groups" },
      {
        label: "코드그룹 신규 등록",
        kind: "create",
        description: "POST /api/code-groups",
      },
      {
        label: "상세코드 목록",
        kind: "navigate",
        description: "선택 groupId를 유지하고 /admin/codes로 이동",
      },
    ],
  }),
  screen({
    id: "SCR-011-codes",
    route: "/admin/codes",
    title: "상세코드 관리",
    apiPath: "/api/detail-codes",
    menuPath: "시스템 관리 > 공통코드 관리 > 상세코드 관리",
    topMenu: "시스템 관리",
    middleMenu: "공통코드 관리",
    entity: "codes",
    archetype: "search/list/detail",
    goal: "코드그룹별 상세코드를 관리하며 사용 중지 시 물리삭제 대신 useYn=N 저장으로 처리합니다.",
    primaryCta: "상세코드 저장",
    columns: [
      { key: "id", label: "코드값" },
      { key: "codeGroupId", label: "코드그룹" },
      { key: "title", label: "코드명" },
      { key: "parentCode", label: "상위코드" },
      { key: "sortOrder", label: "정렬순서" },
      { key: "extraAttributes", label: "추가속성" },
      { key: "useYn", label: "사용여부" },
    ],
    editableFields: [
      { key: "codeGroupId", label: "코드그룹" },
      { key: "id", label: "코드값" },
      { key: "title", label: "코드명" },
      { key: "parentCode", label: "상위코드" },
      { key: "sortOrder", label: "정렬순서", type: "number" },
      { key: "extraAttributes", label: "추가속성", type: "textarea" },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-012-system-settings",
    route: "/admin/system-settings",
    title: "공통 환경설정",
    apiPath: "/api/configurations",
    menuPath: "시스템 관리 > 시스템 환경설정 > 공통 환경설정",
    topMenu: "시스템 관리",
    middleMenu: "시스템 환경설정",
    entity: "system_settings",
    archetype: "search/list/detail",
    goal: "공통 환경설정 항목별 현재 값과 단위를 확인하고 항목 단위에 맞는 값만 수정합니다.",
    primaryCta: "설정값 저장",
    supportsCreate: false,
    columns: [
      { key: "id", label: "config_key" },
      { key: "title", label: "설정 항목" },
      { key: "configValue", label: "현재 값" },
      { key: "unit", label: "단위" },
      { key: "description", label: "설명" },
      { key: "useYn", label: "사용여부" },
    ],
    editableFields: [
      { key: "id", label: "config_key" },
      { key: "title", label: "설정 항목" },
      { key: "configValue", label: "현재 값" },
      { key: "unit", label: "단위" },
      { key: "description", label: "설명", type: "textarea" },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-013-base-years",
    route: "/admin/base-years",
    title: "기준연도 관리",
    apiPath: "/api/base-years",
    menuPath: "시스템 관리 > 시스템 환경설정 > 기준연도 관리",
    topMenu: "시스템 관리",
    middleMenu: "시스템 환경설정",
    entity: "base_years",
    archetype: "search/list/detail",
    goal: "기준연도와 현재 평가연도/기본 조회연도, 복사·초기화 정책을 관리합니다. 평가자료 직접 변경 action은 제공하지 않습니다.",
    primaryCta: "기준연도 저장",
    columns: [
      { key: "id", label: "기준연도" },
      { key: "currentEvaluationYearYn", label: "현재 평가연도" },
      { key: "defaultSearchYearYn", label: "기본 조회연도" },
      { key: "copyOrInitializePolicy", label: "복사/초기화 정책" },
      { key: "status", label: "상태" },
      { key: "updatedAt", label: "수정일시" },
    ],
    editableFields: [
      { key: "id", label: "base_year" },
      {
        key: "currentEvaluationYearYn",
        label: "현재 평가연도",
        type: "select",
        options: ynOptions,
      },
      {
        key: "defaultSearchYearYn",
        label: "기본 조회연도",
        type: "select",
        options: ynOptions,
      },
      {
        key: "copyOrInitializePolicy",
        label: "복사/초기화 정책",
        type: "textarea",
      },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-014-file-policies",
    route: "/admin/file-policies",
    title: "파일정책 관리",
    apiPath: "/api/file-policies",
    menuPath: "시스템 관리 > 시스템 환경설정 > 파일정책 관리",
    topMenu: "시스템 관리",
    middleMenu: "시스템 환경설정",
    entity: "file_policies",
    archetype: "search/list/detail",
    goal: "업무별 허용 확장자, 용량, 첨부 개수, 파일명 길이, 악성파일 검사 정책을 관리합니다. 실제 파일 업로드 action은 제공하지 않습니다.",
    primaryCta: "파일정책 저장",
    columns: [
      { key: "businessArea", label: "업무구분" },
      { key: "allowedExtensions", label: "허용 확장자" },
      { key: "maxSingleFileSize", label: "단일 최대용량" },
      { key: "maxFilesPerRecord", label: "건당 첨부개수" },
      { key: "maxTotalSize", label: "전체용량" },
      { key: "maxFilenameLength", label: "파일명 길이" },
      { key: "malwareScanRequiredYn", label: "악성검사" },
    ],
    editableFields: [
      { key: "id", label: "정책ID" },
      { key: "businessArea", label: "업무구분" },
      { key: "allowedExtensions", label: "허용 확장자" },
      { key: "maxSingleFileSize", label: "단일 최대용량", type: "number" },
      { key: "maxFilesPerRecord", label: "건당 첨부개수", type: "number" },
      { key: "maxTotalSize", label: "전체용량", type: "number" },
      { key: "maxFilenameLength", label: "파일명 최대길이", type: "number" },
      {
        key: "malwareScanRequiredYn",
        label: "악성파일 검사",
        type: "select",
        options: ynOptions,
      },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-015-notices",
    route: "/admin/notices",
    title: "공지사항 관리",
    apiPath: "/api/notices",
    menuPath: "시스템 관리 > 공지·도움말 관리 > 공지사항 관리",
    topMenu: "시스템 관리",
    middleMenu: "공지·도움말 관리",
    entity: "notices",
    archetype: "search/list/detail",
    goal: "공지 제목·내용·게시기간·대상 역할/조직·중요여부·첨부파일 연결을 관리합니다. 열람이 업무 승인/확인처리로 이어지지 않습니다.",
    primaryCta: "공지 저장",
    columns: [
      { key: "title", label: "제목" },
      { key: "postStartAt", label: "게시 시작" },
      { key: "postEndAt", label: "게시 종료" },
      { key: "targetRoleCode", label: "대상 역할" },
      { key: "targetOrganizationCode", label: "대상 조직" },
      { key: "importantYn", label: "중요" },
      { key: "attachmentGroupId", label: "첨부파일" },
      { key: "status", label: "상태" },
    ],
    editableFields: [
      { key: "id", label: "공지ID" },
      { key: "title", label: "제목" },
      { key: "content", label: "내용", type: "textarea" },
      { key: "postStartAt", label: "게시 시작", type: "date" },
      { key: "postEndAt", label: "게시 종료", type: "date" },
      { key: "targetRoleCode", label: "대상 역할" },
      { key: "targetOrganizationCode", label: "대상 조직" },
      {
        key: "importantYn",
        label: "중요여부",
        type: "select",
        options: ynOptions,
      },
      { key: "attachmentGroupId", label: "첨부파일 그룹" },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-016-attachments",
    route: "/admin/attachments",
    title: "첨부파일 관리",
    apiPath: "/api/attachments",
    menuPath: "파일·데이터 관리 > 첨부파일 관리 > 첨부파일 관리",
    topMenu: "파일·데이터 관리",
    middleMenu: "첨부파일 관리",
    entity: "attachments",
    archetype: "file-integrity",
    goal: "첨부파일 메타정보와 악성검사·삭제상태를 조회하고 사유 입력 후 논리삭제합니다. 정합성 점검은 자동 삭제하지 않습니다.",
    primaryCta: "논리삭제 처리",
    supportsCreate: false,
    columns: [
      { key: "id", label: "file_id" },
      { key: "attachmentGroupId", label: "그룹ID" },
      { key: "businessArea", label: "업무구분" },
      { key: "businessRecordId", label: "업무자료 키" },
      { key: "originalFilename", label: "원본명" },
      { key: "storedFilename", label: "저장명" },
      { key: "extension", label: "확장자" },
      { key: "fileSize", label: "크기" },
      { key: "malwareScanResult", label: "악성검사" },
      { key: "deleteYn", label: "삭제상태" },
    ],
    editableFields: [
      { key: "id", label: "file_id" },
      { key: "title", label: "파일명" },
      {
        key: "deleteYn",
        label: "논리삭제",
        type: "select",
        options: ynOptions,
      },
      { key: "deleteReason", label: "삭제사유", type: "textarea" },
      {
        key: "finalizedRecordYn",
        label: "평가확정 자료 여부",
        type: "select",
        options: ynOptions,
      },
    ],
    actions: [
      { label: "검색", kind: "local", description: "GET /api/attachments" },
      { label: "상세", kind: "readonly", description: "파일 메타정보 확인" },
      {
        label: "논리삭제",
        kind: "logicalDelete",
        description: "deleteYn=Y 및 deleteReason으로 POST /api/attachments",
      },
      {
        label: "정합성 점검",
        kind: "local",
        description: "자동 삭제 없이 화면 안내만 표시",
      },
    ],
  }),
  screen({
    id: "SCR-017-upload-templates",
    route: "/admin/upload-templates",
    title: "업로드 양식 관리",
    apiPath: "/api/excel/templates",
    menuPath: "파일·데이터 관리 > 엑셀 관리 > 업로드 양식 관리",
    topMenu: "파일·데이터 관리",
    middleMenu: "엑셀 관리",
    entity: "upload_templates",
    archetype: "search/list/detail",
    goal: "업무별 엑셀 업로드 양식 버전과 필수 열·열 순서·코드값 규칙·시행일·다운로드 파일 연결을 관리합니다.",
    primaryCta: "업로드 양식 저장",
    oqNotice: "실제 binary 다운로드 endpoint는 OQ-UI-017-01로 보존합니다.",
    columns: [
      { key: "templateId", label: "template_id" },
      { key: "businessArea", label: "업무구분" },
      { key: "version", label: "버전" },
      { key: "requiredColumns", label: "필수 열" },
      { key: "columnOrder", label: "열 순서" },
      { key: "codeValueRules", label: "코드값 규칙" },
      { key: "effectiveDate", label: "시행일" },
      { key: "downloadFileId", label: "다운로드 파일" },
      { key: "status", label: "상태" },
    ],
    editableFields: [
      { key: "id", label: "template_id" },
      { key: "businessArea", label: "업무구분" },
      { key: "version", label: "버전" },
      { key: "requiredColumns", label: "필수 열", type: "textarea" },
      { key: "columnOrder", label: "열 순서", type: "textarea" },
      { key: "codeValueRules", label: "코드값 규칙", type: "textarea" },
      { key: "effectiveDate", label: "시행일", type: "date" },
      { key: "downloadFileId", label: "다운로드 파일ID" },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-018-excel-uploads",
    route: "/admin/excel-uploads",
    title: "엑셀 업로드",
    apiPath: "/api/excel/uploads",
    menuPath: "파일·데이터 관리 > 엑셀 관리 > 엑셀 업로드",
    topMenu: "파일·데이터 관리",
    middleMenu: "엑셀 관리",
    entity: "excel_uploads",
    archetype: "upload wizard",
    goal: "업무 양식과 XLSX 파일 선택 후 사전 검증/업로드 결과와 오류 행 안내를 확인합니다.",
    primaryCta: "사전 검증 및 업로드",
    oqNotice:
      "OpenAPI requestBody가 JSON Entity이므로 실제 파일 전송 형식과 오류목록 다운로드 endpoint는 OQ로 표시합니다.",
    columns: [
      { key: "id", label: "upload_id" },
      { key: "uploadedBy", label: "업로더" },
      { key: "uploadedAt", label: "일시" },
      { key: "filename", label: "파일명" },
      { key: "totalCount", label: "총건수" },
      { key: "normalCount", label: "정상" },
      { key: "errorCount", label: "오류" },
      { key: "excludedCount", label: "제외" },
      { key: "savedCount", label: "저장" },
      { key: "processingTimeMs", label: "처리시간" },
      { key: "status", label: "상태" },
    ],
    editableFields: [
      { key: "id", label: "upload_id" },
      { key: "templateId", label: "template_id" },
      { key: "filename", label: "파일명(.xlsx)" },
      { key: "reason", label: "업로드 사유", type: "textarea" },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-019-excel-downloads",
    route: "/admin/excel-downloads",
    title: "엑셀 다운로드",
    apiPath: "/api/excel/downloads",
    menuPath: "파일·데이터 관리 > 엑셀 관리 > 엑셀 다운로드",
    topMenu: "파일·데이터 관리",
    middleMenu: "엑셀 관리",
    entity: "excel_downloads",
    archetype: "search/list/detail",
    goal: "현재 조회조건과 서버 데이터 범위 권한을 적용한 XLSX 생성·다운로드 요청을 관리합니다.",
    primaryCta: "현재 조회조건으로 엑셀 생성",
    supportsCreate: false,
    oqNotice:
      "화면 세부 필터·컬럼명은 OQ-UI-019-01로 보존하며 임의 업무자료 변경 payload를 만들지 않습니다.",
    columns: [
      { key: "id", label: "request_id" },
      { key: "querySummary", label: "조회조건" },
      { key: "dataScopeAppliedYn", label: "데이터범위 적용" },
      { key: "filename", label: "파일명" },
      { key: "status", label: "상태" },
      { key: "createdAt", label: "요청일시" },
    ],
    editableFields: [
      { key: "id", label: "request_id" },
      { key: "querySummary", label: "조회조건 요약", type: "textarea" },
      {
        key: "dataScopeAppliedYn",
        label: "데이터범위 적용",
        type: "select",
        options: ynOptions,
      },
      { key: "filename", label: "파일명" },
      { key: "reason", label: "생성 사유", type: "textarea" },
      { key: "status", label: "상태", type: "select", options: statusOptions },
    ],
  }),
  screen({
    id: "SCR-020-personal-information",
    route: "/admin/personal-information",
    title: "개인정보 관리",
    apiPath: "/api/privacy/policies",
    menuPath: "보안·감사 관리 > 개인정보 관리 > 개인정보 관리",
    topMenu: "보안·감사 관리",
    middleMenu: "개인정보 관리",
    entity: "personal_information",
    archetype: "search/list/detail",
    goal: "개인정보 항목별 보호정책과 역할별 조회·출력 권한을 관리하고 처리이력은 read-only로 확인합니다.",
    primaryCta: "보호정책 저장",
    supportsCreate: false,
    readonlyNotice: "실제 사용자 개인정보 원문값은 표시·수정하지 않습니다.",
    secondaryApis: [
      { label: "역할별 권한", path: "/api/privacy/permissions" },
      { label: "처리이력", path: "/api/privacy/access-history" },
    ],
    columns: [
      { key: "fieldName", label: "개인정보 항목" },
      { key: "privacyGrade", label: "등급" },
      { key: "encryptionRequiredYn", label: "암호화" },
      { key: "maskingRequiredYn", label: "마스킹" },
      { key: "logExclusionYn", label: "로그 제외" },
      { key: "useYn", label: "사용여부" },
    ],
    editableFields: [
      { key: "id", label: "policy_id" },
      { key: "fieldName", label: "개인정보 항목" },
      { key: "privacyGrade", label: "등급" },
      {
        key: "encryptionRequiredYn",
        label: "암호화",
        type: "select",
        options: ynOptions,
      },
      {
        key: "maskingRequiredYn",
        label: "마스킹",
        type: "select",
        options: ynOptions,
      },
      {
        key: "logExclusionYn",
        label: "로그 제외",
        type: "select",
        options: ynOptions,
      },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-021-active-sessions",
    route: "/admin/active-sessions",
    title: "접속현황 관리",
    apiPath: "/api/sessions",
    menuPath: "보안·감사 관리 > 접속기록 관리 > 접속현황 관리",
    topMenu: "보안·감사 관리",
    middleMenu: "접속기록 관리",
    entity: "active_sessions",
    archetype: "audit-log viewer",
    goal: "현재 활성 세션과 종료이력을 조회하고 사유 입력 후 강제종료합니다. 종료이력은 수정·삭제할 수 없습니다.",
    primaryCta: "강제종료",
    supportsCreate: false,
    readonlyNotice: "종료이력은 read-only입니다.",
    secondaryApis: [{ label: "종료이력", path: "/api/session-terminations" }],
    columns: [
      { key: "id", label: "session_id" },
      { key: "loginId", label: "사용자ID" },
      { key: "title", label: "사용자" },
      { key: "createdAt", label: "로그인시각" },
      { key: "updatedAt", label: "최종활동" },
      { key: "ipAddress", label: "IP" },
      { key: "status", label: "세션상태" },
    ],
    editableFields: [
      { key: "id", label: "session_id" },
      {
        key: "status",
        label: "세션상태",
        type: "select",
        options: ["TERMINATED"],
      },
      { key: "reason", label: "강제종료 사유", type: "textarea" },
    ],
    actions: [
      { label: "검색", kind: "local", description: "GET /api/sessions" },
      { label: "세션 상세", kind: "readonly", description: "read-only 상세" },
      {
        label: "강제종료",
        kind: "terminate",
        description: "사유와 함께 POST /api/sessions",
      },
    ],
  }),
  screen({
    id: "SCR-022-audit-logs",
    route: "/admin/audit-logs",
    title: "감사 로그 관리",
    apiPath: "/api/audit-logs",
    menuPath: "보안·감사 관리 > 감사로그 관리 > 감사 로그 관리",
    topMenu: "보안·감사 관리",
    middleMenu: "감사로그 관리",
    entity: "audit_logs",
    archetype: "audit-log viewer",
    goal: "업무처리·중요정보 조회·권한변경 로그를 유형별로 검색하고 상세는 read-only로 확인합니다.",
    primaryCta: "감사로그 검색",
    readonlyNotice:
      "감사로그 수정·삭제, 원업무 재실행·취소, 보호대상 원문값 표시는 제공하지 않습니다.",
    noMutation: true,
    columns: [
      { key: "id", label: "audit_id" },
      { key: "action", label: "행위" },
      { key: "targetArea", label: "대상영역" },
      { key: "targetId", label: "대상키" },
      { key: "actorLoginId", label: "처리자" },
      { key: "reason", label: "사유" },
      { key: "createdAt", label: "처리일시" },
      { key: "status", label: "결과" },
    ],
    editableFields: [],
    actions: [
      {
        label: "업무처리 로그 검색",
        kind: "readonly",
        description: "GET /api/audit-logs",
      },
      {
        label: "중요정보 조회로그 검색",
        kind: "readonly",
        description: "GET /api/audit-logs",
      },
      {
        label: "권한변경 로그 검색",
        kind: "readonly",
        description: "GET /api/audit-logs",
      },
    ],
  }),
  screen({
    id: "SCR-023-batch-definitions",
    route: "/admin/batch-definitions",
    title: "배치 정의 관리",
    apiPath: "/api/batch-definitions",
    menuPath: "시스템 운영 관리 > 배치작업 관리 > 배치 정의 관리",
    topMenu: "시스템 운영 관리",
    middleMenu: "배치작업 관리",
    entity: "batch_definitions",
    archetype: "search/list/detail",
    goal: "배치ID·실행주기·선후행·파라미터·최대실행시간·담당자를 관리합니다. 즉시 실행·중지·재실행은 제공하지 않습니다.",
    primaryCta: "배치 정의 저장",
    columns: [
      { key: "id", label: "batch_id" },
      { key: "schedule", label: "실행주기" },
      { key: "predecessors", label: "선후행" },
      { key: "parameters", label: "파라미터" },
      { key: "maxExecutionTime", label: "최대실행시간" },
      { key: "ownerUserId", label: "담당자" },
      { key: "useYn", label: "사용여부" },
    ],
    editableFields: [
      { key: "id", label: "batch_id" },
      { key: "schedule", label: "실행주기" },
      { key: "predecessors", label: "선후행", type: "textarea" },
      { key: "parameters", label: "파라미터", type: "textarea" },
      { key: "maxExecutionTime", label: "최대실행시간", type: "number" },
      { key: "ownerUserId", label: "담당자" },
      { key: "useYn", label: "사용여부", type: "select", options: ynOptions },
    ],
  }),
  screen({
    id: "SCR-024-batch-executions",
    route: "/admin/batch-executions",
    title: "배치 실행 관리",
    apiPath: "/api/batch-executions",
    menuPath: "시스템 운영 관리 > 배치작업 관리 > 배치 실행 관리",
    topMenu: "시스템 운영 관리",
    middleMenu: "배치작업 관리",
    entity: "batch_executions",
    archetype: "batch operation",
    goal: "실행 가능한 배치의 수동 실행·중지·재실행을 사유와 함께 요청하고 실행상태를 재조회합니다.",
    primaryCta: "실행 요청 저장",
    supportsCreate: false,
    readonlyNotice:
      "배치 정의·실행주기·선후행 관계와 실패 원천 업무자료는 이 화면에서 변경하지 않습니다.",
    columns: [
      { key: "id", label: "execution_id" },
      { key: "batchId", label: "batch_id" },
      { key: "status", label: "실행상태" },
      { key: "executionType", label: "처리유형" },
      { key: "parameters", label: "파라미터" },
      { key: "reason", label: "사유" },
      { key: "executedBy", label: "실행자" },
      { key: "startedAt", label: "시작일시" },
      { key: "endedAt", label: "종료일시" },
      { key: "originalExecutionId", label: "원실행ID" },
    ],
    editableFields: [
      { key: "id", label: "execution_id" },
      { key: "batchId", label: "batch_id" },
      {
        key: "executionType",
        label: "처리유형",
        type: "select",
        options: ["MANUAL", "STOP", "RERUN"],
      },
      { key: "parameters", label: "파라미터", type: "textarea" },
      { key: "reason", label: "사유", type: "textarea" },
      { key: "originalExecutionId", label: "원실행ID" },
    ],
  }),
  screen({
    id: "SCR-025-batch-results",
    route: "/admin/batch-results",
    title: "배치 결과 조회",
    apiPath: "/api/batch-results",
    menuPath: "시스템 운영 관리 > 배치작업 관리 > 배치 결과 조회",
    topMenu: "시스템 운영 관리",
    middleMenu: "배치작업 관리",
    entity: "batch_results",
    archetype: "audit-log viewer",
    goal: "배치 실행ID별 처리건수·성공·실패·제외·소요시간과 연결 로그파일을 조회합니다.",
    primaryCta: "배치 결과 검색",
    readonlyNotice:
      "결과 조회 전용 화면이며 재실행, 실패자료 변경, 로그 수정·삭제 action을 표시하지 않습니다.",
    noMutation: true,
    columns: [
      { key: "batchExecutionId", label: "batch_execution_id" },
      { key: "batchId", label: "batch_id" },
      { key: "startedAt", label: "시작" },
      { key: "endedAt", label: "종료" },
      { key: "processedCount", label: "처리" },
      { key: "successCount", label: "성공" },
      { key: "failureCount", label: "실패" },
      { key: "excludedCount", label: "제외" },
      { key: "durationMs", label: "소요시간" },
      { key: "logFileId", label: "로그파일" },
    ],
    editableFields: [],
    actions: [
      {
        label: "결과 상세",
        kind: "readonly",
        description: "read-only 결과 상세",
      },
      {
        label: "로그파일 상세",
        kind: "readonly",
        description: "read-only 로그 metadata",
      },
    ],
  }),
] as const;

export type Screen = (typeof screens)[number];

export const navigationGroups = Array.from(
  screens.reduce((topMap, item) => {
    if (!topMap.has(item.topMenu))
      topMap.set(item.topMenu, new Map<string, ScreenConfig[]>());
    const middleMap = topMap.get(item.topMenu)!;
    if (!middleMap.has(item.middleMenu)) middleMap.set(item.middleMenu, []);
    middleMap.get(item.middleMenu)!.push(item);
    return topMap;
  }, new Map<string, Map<string, ScreenConfig[]>>()),
).map(([topMenu, middleMap]) => ({
  topMenu,
  middleMenus: Array.from(middleMap).map(([middleMenu, items]) => ({
    middleMenu,
    items,
  })),
}));
